In [2]:
import pandas as pd
import numpy as np

In [3]:
ArtInfo = pd.read_csv ('Art_Object_Info_NotClean.csv')

In [4]:
ArtInfo.head()

,Artist,Birth,Death,Art Title,DoC,Estimate,price,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,"USD 40,000 – USD 60,000","USD 81,250",(73 x 54 cm.),17-Nov-16,2016 | LIVE AUCTION 12147\nIMPRESSIONIST & MOD...
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,"GBP 1,200 - GBP 1,800","GBP 2,125",(34.6 x 24.7 cm.),18-Dec-17,4 Dec - 18 Dec 2017 | Online Auction 15547\nTh...
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,"USD 300,000 – USD 500,000","USD 663,750",(304.8 x 208.2 cm.),16-May-13,2013 | LIVE AUCTION 2786\nPOST-WAR & CONTEMPOR...
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,"GBP 12,000 – GBP 18,000","GBP 21,250",(66 x 91.4 cm.),13-Dec-12,2012 | LIVE AUCTION 5969\nVICTORIAN & BRITISH ...
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,"GBP 3,000 - GBP 5,000","GBP 7,500",(35.3 x 27.7cm.),20-Sep-18,12 Sep - 20 Sep 2018 | Online Auction 16454\nF...

In [5]:
def GBP_to_Dolar(amount):
    dollars = amount * 1.25
    return dollars

In [6]:
def EUR_to_Dolar(amount):
    dollars = amount * 1.05
    return dollars

In [7]:
def HKD_to_Dolar(amount):
    dollars = amount * 0.13
    return dollars

In [8]:
def CHF_to_Dolar(amount):
    dollars = amount * 1.02
    return dollars

In [9]:
def CNY_to_Dolar(amount):
    dollars = amount * 0.15
    return dollars

## Gets the currency from the estimate and makes it a feature

In [10]:
currency = []
for estimates in ArtInfo["Estimate"]:
    try:
        splitEstimate = estimates.split()
        currency.append(splitEstimate[0])
    except:
        currency.append("0")
        
ArtInfo.insert(loc=5, column='Currency', value=currency)

## Makes the price feature as a float

In [11]:
price_list = []

for price in ArtInfo["price"]:
    try:
        splitPrice = price.split()
        price_list.append(splitPrice[1])
    except:
        price_list.append("0")

float_prices = []   

for price in price_list:
    No_commas = price.replace(",", "")
    No_commas = float(No_commas)
    float_prices.append(No_commas)
        
ArtInfo["price"] = float_prices

## splits between low and high estimates

In [12]:
low_high = []
low_estimate = []
high_estimate = []


for a,b in zip(ArtInfo["Currency"], ArtInfo["Estimate"]): 
    b = b.replace(",", "")
    b = b.replace(a, "")
    b = b.replace("–", "")
    b = b.replace("-", "") 
    b = b.replace("   ", " ")
    
    try:
        low_estimate.append(float(b.split()[0]))
    except:
        low_estimate.append(0)
        
    try:
        high_estimate.append(float(b.split()[1]))
    except:
        high_estimate.append(0)       
        
ArtInfo.insert(loc=8, column='low_estimate', value=low_estimate)
ArtInfo.insert(loc=9, column='high_estimate', value=high_estimate)
ArtInfo.drop('Estimate', inplace=True, axis=1)

In [13]:
ArtInfo.head(50)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.0,40000.0,60000.0,(73 x 54 cm.),17-Nov-16,2016 | LIVE AUCTION 12147\nIMPRESSIONIST & MOD...
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,GBP,2125.0,1200.0,1800.0,(34.6 x 24.7 cm.),18-Dec-17,4 Dec - 18 Dec 2017 | Online Auction 15547\nTh...
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.0,300000.0,500000.0,(304.8 x 208.2 cm.),16-May-13,2013 | LIVE AUCTION 2786\nPOST-WAR & CONTEMPOR...
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,GBP,21250.0,12000.0,18000.0,(66 x 91.4 cm.),13-Dec-12,2012 | LIVE AUCTION 5969\nVICTORIAN & BRITISH ...
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,GBP,7500.0,3000.0,5000.0,(35.3 x 27.7cm.),20-Sep-18,12 Sep - 20 Sep 2018 | Online Auction 16454\nF...
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.0,30000.0,50000.0,(182.9 x 152.4 cm.),27-Sep-18,2018 | LIVE AUCTION 15877\nPOST-WAR TO PRESENT
6,JAN DERK HUIBERS,0,0,Cup of warmth,0,GBP,6000.0,2000.0,3000.0,(77.5 x 61.5 cm.),16-Dec-21,2 Dec - 16 Dec 2021 | Online Auction 20112\nBr...
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.0,3000000.0,5000000.0,(243.8 x 152.4 cm.),13-May-15,2015 | LIVE AUCTION 3740\nPOST-WAR AND CONTEMP...
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,GBP,1375.0,1000.0,1500.0,0,4-Dec-13,2013 | LIVE AUCTION 9728\n500 YEARS OF PRINTMA...
9,WILLIAM EGGLESTON,0,0,"Untitled, 1970s",0,USD,11875.0,12000.0,18000.0,(18.4 x 28 cm.),5-Oct-18,2018 | LIVE AUCTION 16382\nPHOTOGRAPHS
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,GBP,1875.0,1000.0,1500.0,(31.1 x 15 cm.),13-Dec-17,2017 | LIVE AUCTION 14233\nVICTORIAN PRE-RAPHA...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,EUR,137500.0,120000.0,160000.0,0,24-Apr-18,2018 | LIVE AUCTION 15805\nPOST-WAR AND CONTEM...
12,Floris van Schooten,0,0,"Cherries, gooseberries, redcurrants, blackcurr...",0,EUR,15000.0,10000.0,15000.0,0,18-Nov-15,2015 | LIVE AUCTION 3058\nOLD MASTERS & 19TH C...
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,EUR,39900.0,20000.0,30000.0,0,31-Mar-16,2016 | LIVE AUCTION 12610\nOEUVRES MODERNES SU...
14,Lucebert,1924,1994,Untitled,0,EUR,6930.0,4000.0,6000.0,0,26-Apr-22,12 Apr - 26 Apr 2022 | Online Auction 20823\n2...
15,Adam Colonia,Rotterdam,1685,The Annunciation to the Shepherds,0,EUR,5000.0,4000.0,6000.0,0,14-May-14,"2014 | LIVE AUCTION 3047\nOLD MASTERS, 19TH CE..."
16,Cornelius Jonson van Ceulen and Studio,London,1661,"Portrait of a gentleman, possibly Philip Herbe...",0,GBP,3250.0,3000.0,5000.0,(74.9 x 62.2 cm.),29-Oct-15,2015 | LIVE AUCTION 10451\nOLD MASTER & BRITIS...
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.0,100000.0,150000.0,(52.5 x 37.2 cm.),5-Nov-13,2013 | LIVE AUCTION 3443\nA DIALOGUE THROUGH A...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.0,60000.0,80000.0,(30.5 x 30.5 cm.),16-May-19,2019 | LIVE AUCTION 16979\nPOST-WAR AND CONTEM...
19,ILSE BING,0,0,"Two street fair views, Paris, 1933",0,USD,2500.0,4000.0,6000.0,(28.2 x 19.6 cm.),7-Dec-17,29 Nov - 7 Dec 2017 | Online Auction 15575\nMo...
20,Nicolas Party,1980,0,Still Life No 103,2012,GBP,8500.0,2000.0,3000.0,(16.5 x 22.2cm.),28-Jun-18,2018 | LIVE AUCTION 15893\nPOST-WAR TO PRESENT
21,Samuel Holburn Fyfe,1822,1905,The clipper John R. Worcester outward-bound fr...,0,GBP,3125.0,2500.0,3500.0,(71 x 111.8 cm.),5-Jun-14,2014 | LIVE AUCTION 5317\nMARITIME ART
22,"JOHN FERNELEY, SEN.",BRITISH,1860,"Master John Marriott on a grey horse, with his...",0,GBP,27500.0,20000.0,30000.0,(78.8 x 95.9 cm.),29-Jul-20,7 Jul - 29 Jul 2020 | Online Auction 18829\nBr...
23,Pedro Friedeberg,1936,0,Pair of Hand Chairs,0,USD,18750.0,15000.0,20000.0,(86.4 x 48.3 x 50.8 cm.),30-May-18,18 May - 30 May 2018 | Online Auction 15729\nL...
24,Gunther Gerzso,1915,2000,Trópico calizo,1992,USD,137500.0,70000.0,90000.0,(81.3 x 100.3 cm.),30-Jul-20,2020 | LIVE AUCTION 18183\nLATIN AMERICAN ART
25,BRASSAÏ,1899,1950,"Graffiti (Serie IV, Masques et Visages), 1935-...",0,USD,18750.0,10000.0,15000.0,(40 x 30.4 cm.),14-Oct-20,5 Oct - 14 Oct 2020 | Online Auction 19790\nTh...
26,ANDY WARHOL,1928,1987,Marilyn Monroe (Marilyn): one print,0,USD,187500.0,100000.0,150000.0,(914 x 914 mm.),22-Oct-21,2021 | LIVE AUCTION 19997\nPRINTS & MULTIPLES
27,ARMAN,1928,2005,Sans titre,0,EUR,750.0,1200.0,1800.0,(13 5/8 x 21¼ in.),26-Oct-13,2013 | LIVE AUCTION 3536\nDAGNY ET JAN RUNNQVI...
28,ANDY WARHOL,1928,1987,Marilyn Monroe (Marilyn): one print,0,USD,100000.0,80000.0,120000.0,(914 x 914 mm.),23-Oct-19,2019 | LIVE AUCTION 17127\nPRINTS & MULTIPLES
29,Pablo Picasso,1881,1973,Verve,0,USD,68750.0,30000.0,50000.0,(35.6 x 26.5 cm.),16-May-18,2018 | LIVE AUCTION 15972\nIMPRESSIONIST AND M...
30,Walter Leblanc,1932,1986,Twisted Strings TX. 171,1971,EUR,83750.0,70000.0,90000.0,0,1-May-19,2019 | LIVE AUCTION 17372\nPOST-WAR & CONTEMPO...
31,Bernard Buffet,1928,1999,Compotier sur un plateau,1991,GBP,73250.0,60000.0,80000.0,(73 x 92 cm.),21-Jun-12,2012 | LIVE AUCTION 5472\nIMPRESSIONIST/MODERN...
32,Jean Paul Riopelle,1923,2002,P.M.12,1960,EUR,567000.0,50000.0,70000.0,0,13-Apr-22,APRIL 13 | LIVE AUCTION 21429\nCOLLECTION JACQ...
33,Gavin Turk,1967,0,Cave,1997,GBP,50000.0,40000.0,60000.0,(on the reverse),30-Jun-16,2016 | LIVE AUCTION 11798\nPOST-WAR AND CONTEM...
34,KATHERINE BERNHARDT,0,0,Female Obsession Night Naked,2005,GBP,23750.0,6000.0,8000.0,(80 x 120cm.),7-Jul-21,24 Jun - 7 Jul 2021 | Online Auction 19114\nFi...
35,MASTER MZ,0,0,The Martyrdom of Saint Catherine,0,USD,6250.0,7000.0,10000.0,0,29-Jan-19,2019 | LIVE AUCTION 16544\nOLD MASTER PRINTS
36,Georges Bertin Scott,French,1942,La belle Parisienne,0,GBP,8750.0,8000.0,12000.0,(209 x 90.5 cm.),20-Jan-16,2016 | LIVE AUCTION 11799\n19TH CENTURY EUROPE...
37,Paul Cezanne,1839,1906,Autoportrait,0,GBP,1375.0,1200.0,1800.0,(and similar),4-Dec-14,2014 | LIVE AUCTION 5882\nPRINTS & MULTIPLES
38,Tom Wesselmann,1931,2004,Monica with Wesselmann,1992,GBP,187500.0,120000.0,180000.0,(162.5 x 122.5cm.),7-Oct-17,2017 | LIVE AUCTION 14443\nPOST-WAR AND CONTEM...
39,D'APRES PIET MONDRIAN,1872,1944,Mondrian,0,EUR,6250.0,5000.0,7000.0,0,9-Jun-20,20 May - 9 Jun 2020 | Online Auction 18973\nCo...
40,Amédée Marcel-Clément,1873,0,Moonlit vessels off the coast,0,GBP,5000.0,2000.0,2500.0,(50.3 x 61 cm.),2-May-14,2014 | LIVE AUCTION 5613\n19TH CENTURY EUROPEA...
41,Andy Warhol,1928,1987,Knives,1981,USD,3015000.0,1600000.0,2000000.0,(228.6 x 177.8 cm.),14-Nov-19,2019 | LIVE AUCTION 17650\nPOST-WAR AND CONTEM...
42,WILLIAM EGGLESTON,0,0,"Untitled (Stop Sign), 1980s",0,USD,8750.0,10000.0,15000.0,(18.5 x 28 cm.),2-Apr-19,2019 | LIVE AUCTION 17021\nPHOTOGRAPHS
43,Francis Bacon,1909,1992,Two Men Working in a Field,1971,GBP,10722500.0,7000000.0,10000000.0,(198 x 147cm.),30-Jun-15,2015 | LIVE AUCTION 10381\nPOST-WAR AND CONTEM...
44,Lynn Chadwick,1914,2003,Sitting Figures on Stripes,0,GBP,4000.0,1500.0,2500.0,(19 x 28.2 cm.),11-Jul-13,2013 | LIVE AUCTION 1124\nMODERN BRITISH ART D...
45,PHOEBE UNWIN,0,0,Seen,2014,GBP,1750.0,1000.0,2000.0,(183 x 153cm.),30-Mar-21,18 Mar - 30 Mar 2021 | Online Auction 19113\nF...
46,Giorgio de Chirico,1888,1978,i) Il primo a traversarlo fu l'Ippogrifo quand...,0,GBP,12500.0,12000.0,18000.0,(21 x 15.5 cm.),6-Feb-20,2020 | LIVE AUCTION 18341\nIMPRESSIONIST AND M...
47,Emil Nolde,1867,1956,Porträt eines Mädchens (schwarzes Haar),0,USD,200000.0,80000.0,120000.0,(47.1 x 36 cm.),12-Nov-18,2018 | LIVE AUCTION 15978\nIMPRESSIONIST AND M...
48,PROSPERO FONTANA,BOLOGNA,1597,Phaeton receiving the chariot from Apollo (rec...,0,GBP,750.0,3000.0,5000.0,(31.1 x 21.9 cm),6-Jul-21,2021 | LIVE AUCTION 19450\nOLD MASTER AND BRIT...
49,Alighiero Boetti,1940,1994,Mappa,1990,USD,2167500.0,800000.0,1200000.0,(120.5 x 224.8 cm.),15-Nov-16,2016 | LIVE AUCTION 12156\nPOST-WAR & CONTEMPO...

## currency Conversion using 2022 values (Not perfect)

In [14]:
price_usd = []
low_est_usd = []
high_est_usd = []
currency = []

for cur, price, low_est, high_est in zip(ArtInfo["Currency"], ArtInfo["price"], ArtInfo["low_estimate"], ArtInfo["high_estimate"]):
    if cur == "USD":
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    elif cur == "GBP":
        price = GBP_to_Dolar(price)
        low_est = GBP_to_Dolar(low_est)
        high_est = GBP_to_Dolar(high_est)
        
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    elif cur == "EUR":
        price = EUR_to_Dolar(price)
        low_est = EUR_to_Dolar(low_est)
        high_est = EUR_to_Dolar(high_est)
        
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    elif cur == "HKD":
        price = HKD_to_Dolar(price)
        low_est = HKD_to_Dolar(low_est)
        high_est = HKD_to_Dolar(high_est)
        
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    elif cur == "CNY":
        price = CNY_to_Dolar(price)
        low_est = CNY_to_Dolar(low_est)
        high_est = CNY_to_Dolar(high_est) 
        
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    elif cur == "CHF":
        price = CHF_to_Dolar(price)
        low_est = CHF_to_Dolar(low_est)
        high_est = CHF_to_Dolar(high_est)
        
        currency.append("USD")
        price_usd.append(round(price, 2))
        low_est_usd.append(round(low_est, 2))
        high_est_usd.append(round(high_est, 2))
    else:
        currency.append("Error")
        price_usd.append(0)
        low_est_usd.append(0)
        high_est_usd.append(0)
        

ArtInfo["price"] = price_usd
ArtInfo["low_estimate"] = low_est_usd
ArtInfo["high_estimate"] = high_est_usd
ArtInfo["Currency"] = currency

In [15]:
ArtInfo.head(20)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.00,40000.0,60000.0,(73 x 54 cm.),17-Nov-16,2016 | LIVE AUCTION 12147\nIMPRESSIONIST & MOD...
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,(34.6 x 24.7 cm.),18-Dec-17,4 Dec - 18 Dec 2017 | Online Auction 15547\nTh...
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,(304.8 x 208.2 cm.),16-May-13,2013 | LIVE AUCTION 2786\nPOST-WAR & CONTEMPOR...
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,(66 x 91.4 cm.),13-Dec-12,2012 | LIVE AUCTION 5969\nVICTORIAN & BRITISH ...
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,(35.3 x 27.7cm.),20-Sep-18,12 Sep - 20 Sep 2018 | Online Auction 16454\nF...
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,(182.9 x 152.4 cm.),27-Sep-18,2018 | LIVE AUCTION 15877\nPOST-WAR TO PRESENT
6,JAN DERK HUIBERS,0,0,Cup of warmth,0,USD,7500.00,2500.0,3750.0,(77.5 x 61.5 cm.),16-Dec-21,2 Dec - 16 Dec 2021 | Online Auction 20112\nBr...
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,(243.8 x 152.4 cm.),13-May-15,2015 | LIVE AUCTION 3740\nPOST-WAR AND CONTEMP...
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,0,4-Dec-13,2013 | LIVE AUCTION 9728\n500 YEARS OF PRINTMA...
9,WILLIAM EGGLESTON,0,0,"Untitled, 1970s",0,USD,11875.00,12000.0,18000.0,(18.4 x 28 cm.),5-Oct-18,2018 | LIVE AUCTION 16382\nPHOTOGRAPHS
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,(31.1 x 15 cm.),13-Dec-17,2017 | LIVE AUCTION 14233\nVICTORIAN PRE-RAPHA...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,0,24-Apr-18,2018 | LIVE AUCTION 15805\nPOST-WAR AND CONTEM...
12,Floris van Schooten,0,0,"Cherries, gooseberries, redcurrants, blackcurr...",0,USD,15750.00,10500.0,15750.0,0,18-Nov-15,2015 | LIVE AUCTION 3058\nOLD MASTERS & 19TH C...
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,USD,41895.00,21000.0,31500.0,0,31-Mar-16,2016 | LIVE AUCTION 12610\nOEUVRES MODERNES SU...
14,Lucebert,1924,1994,Untitled,0,USD,7276.50,4200.0,6300.0,0,26-Apr-22,12 Apr - 26 Apr 2022 | Online Auction 20823\n2...
15,Adam Colonia,Rotterdam,1685,The Annunciation to the Shepherds,0,USD,5250.00,4200.0,6300.0,0,14-May-14,"2014 | LIVE AUCTION 3047\nOLD MASTERS, 19TH CE..."
16,Cornelius Jonson van Ceulen and Studio,London,1661,"Portrait of a gentleman, possibly Philip Herbe...",0,USD,4062.50,3750.0,6250.0,(74.9 x 62.2 cm.),29-Oct-15,2015 | LIVE AUCTION 10451\nOLD MASTER & BRITIS...
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.00,100000.0,150000.0,(52.5 x 37.2 cm.),5-Nov-13,2013 | LIVE AUCTION 3443\nA DIALOGUE THROUGH A...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.00,60000.0,80000.0,(30.5 x 30.5 cm.),16-May-19,2019 | LIVE AUCTION 16979\nPOST-WAR AND CONTEM...
19,ILSE BING,0,0,"Two street fair views, Paris, 1933",0,USD,2500.00,4000.0,6000.0,(28.2 x 19.6 cm.),7-Dec-17,29 Nov - 7 Dec 2017 | Online Auction 15575\nMo...

In [16]:
ArtInfo.to_csv("Christies_Art_Objects_Clean.csv", index = False)

## Over_Under_or On Estimate

In [17]:
over_under_est = []

# 1 = over estimate, -1 = under estimate, 0 = in range
for price, low_est, high_est in zip(ArtInfo['price'], ArtInfo['low_estimate'], ArtInfo['high_estimate']):
    if price >= high_est:
        over_under_est.append(1)
    elif price <= low_est:
        over_under_est.append(-1)
    else:
        over_under_est.append(0)
    
ArtInfo.insert(loc=9, column='Est Accuracy', value=over_under_est)

In [18]:
ArtInfo.head(20)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Est Accuracy,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.00,40000.0,60000.0,1,(73 x 54 cm.),17-Nov-16,2016 | LIVE AUCTION 12147\nIMPRESSIONIST & MOD...
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,(34.6 x 24.7 cm.),18-Dec-17,4 Dec - 18 Dec 2017 | Online Auction 15547\nTh...
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,(304.8 x 208.2 cm.),16-May-13,2013 | LIVE AUCTION 2786\nPOST-WAR & CONTEMPOR...
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,(66 x 91.4 cm.),13-Dec-12,2012 | LIVE AUCTION 5969\nVICTORIAN & BRITISH ...
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,(35.3 x 27.7cm.),20-Sep-18,12 Sep - 20 Sep 2018 | Online Auction 16454\nF...
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,1,(182.9 x 152.4 cm.),27-Sep-18,2018 | LIVE AUCTION 15877\nPOST-WAR TO PRESENT
6,JAN DERK HUIBERS,0,0,Cup of warmth,0,USD,7500.00,2500.0,3750.0,1,(77.5 x 61.5 cm.),16-Dec-21,2 Dec - 16 Dec 2021 | Online Auction 20112\nBr...
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,-1,(243.8 x 152.4 cm.),13-May-15,2015 | LIVE AUCTION 3740\nPOST-WAR AND CONTEMP...
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,0,0,4-Dec-13,2013 | LIVE AUCTION 9728\n500 YEARS OF PRINTMA...
9,WILLIAM EGGLESTON,0,0,"Untitled, 1970s",0,USD,11875.00,12000.0,18000.0,-1,(18.4 x 28 cm.),5-Oct-18,2018 | LIVE AUCTION 16382\nPHOTOGRAPHS
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,1,(31.1 x 15 cm.),13-Dec-17,2017 | LIVE AUCTION 14233\nVICTORIAN PRE-RAPHA...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,0,0,24-Apr-18,2018 | LIVE AUCTION 15805\nPOST-WAR AND CONTEM...
12,Floris van Schooten,0,0,"Cherries, gooseberries, redcurrants, blackcurr...",0,USD,15750.00,10500.0,15750.0,1,0,18-Nov-15,2015 | LIVE AUCTION 3058\nOLD MASTERS & 19TH C...
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,USD,41895.00,21000.0,31500.0,1,0,31-Mar-16,2016 | LIVE AUCTION 12610\nOEUVRES MODERNES SU...
14,Lucebert,1924,1994,Untitled,0,USD,7276.50,4200.0,6300.0,1,0,26-Apr-22,12 Apr - 26 Apr 2022 | Online Auction 20823\n2...
15,Adam Colonia,Rotterdam,1685,The Annunciation to the Shepherds,0,USD,5250.00,4200.0,6300.0,0,0,14-May-14,"2014 | LIVE AUCTION 3047\nOLD MASTERS, 19TH CE..."
16,Cornelius Jonson van Ceulen and Studio,London,1661,"Portrait of a gentleman, possibly Philip Herbe...",0,USD,4062.50,3750.0,6250.0,0,(74.9 x 62.2 cm.),29-Oct-15,2015 | LIVE AUCTION 10451\nOLD MASTER & BRITIS...
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.00,100000.0,150000.0,1,(52.5 x 37.2 cm.),5-Nov-13,2013 | LIVE AUCTION 3443\nA DIALOGUE THROUGH A...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.00,60000.0,80000.0,1,(30.5 x 30.5 cm.),16-May-19,2019 | LIVE AUCTION 16979\nPOST-WAR AND CONTEM...
19,ILSE BING,0,0,"Two street fair views, Paris, 1933",0,USD,2500.00,4000.0,6000.0,-1,(28.2 x 19.6 cm.),7-Dec-17,29 Nov - 7 Dec 2017 | Online Auction 15575\nMo...

## Sold vs Unsold

In [19]:
sold = []
for items in ArtInfo["price"]:
    if items == 0:
        sold.append(0)
    else:
        sold.append(1)
        
ArtInfo.insert(loc=9, column='Sold', value=sold)

In [20]:
ArtInfo.head(20)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Sold,Est Accuracy,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.00,40000.0,60000.0,1,1,(73 x 54 cm.),17-Nov-16,2016 | LIVE AUCTION 12147\nIMPRESSIONIST & MOD...
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,1,(34.6 x 24.7 cm.),18-Dec-17,4 Dec - 18 Dec 2017 | Online Auction 15547\nTh...
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,1,(304.8 x 208.2 cm.),16-May-13,2013 | LIVE AUCTION 2786\nPOST-WAR & CONTEMPOR...
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,1,(66 x 91.4 cm.),13-Dec-12,2012 | LIVE AUCTION 5969\nVICTORIAN & BRITISH ...
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,1,(35.3 x 27.7cm.),20-Sep-18,12 Sep - 20 Sep 2018 | Online Auction 16454\nF...
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,1,1,(182.9 x 152.4 cm.),27-Sep-18,2018 | LIVE AUCTION 15877\nPOST-WAR TO PRESENT
6,JAN DERK HUIBERS,0,0,Cup of warmth,0,USD,7500.00,2500.0,3750.0,1,1,(77.5 x 61.5 cm.),16-Dec-21,2 Dec - 16 Dec 2021 | Online Auction 20112\nBr...
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,1,-1,(243.8 x 152.4 cm.),13-May-15,2015 | LIVE AUCTION 3740\nPOST-WAR AND CONTEMP...
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,1,0,0,4-Dec-13,2013 | LIVE AUCTION 9728\n500 YEARS OF PRINTMA...
9,WILLIAM EGGLESTON,0,0,"Untitled, 1970s",0,USD,11875.00,12000.0,18000.0,1,-1,(18.4 x 28 cm.),5-Oct-18,2018 | LIVE AUCTION 16382\nPHOTOGRAPHS
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,1,1,(31.1 x 15 cm.),13-Dec-17,2017 | LIVE AUCTION 14233\nVICTORIAN PRE-RAPHA...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,1,0,0,24-Apr-18,2018 | LIVE AUCTION 15805\nPOST-WAR AND CONTEM...
12,Floris van Schooten,0,0,"Cherries, gooseberries, redcurrants, blackcurr...",0,USD,15750.00,10500.0,15750.0,1,1,0,18-Nov-15,2015 | LIVE AUCTION 3058\nOLD MASTERS & 19TH C...
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,USD,41895.00,21000.0,31500.0,1,1,0,31-Mar-16,2016 | LIVE AUCTION 12610\nOEUVRES MODERNES SU...
14,Lucebert,1924,1994,Untitled,0,USD,7276.50,4200.0,6300.0,1,1,0,26-Apr-22,12 Apr - 26 Apr 2022 | Online Auction 20823\n2...
15,Adam Colonia,Rotterdam,1685,The Annunciation to the Shepherds,0,USD,5250.00,4200.0,6300.0,1,0,0,14-May-14,"2014 | LIVE AUCTION 3047\nOLD MASTERS, 19TH CE..."
16,Cornelius Jonson van Ceulen and Studio,London,1661,"Portrait of a gentleman, possibly Philip Herbe...",0,USD,4062.50,3750.0,6250.0,1,0,(74.9 x 62.2 cm.),29-Oct-15,2015 | LIVE AUCTION 10451\nOLD MASTER & BRITIS...
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.00,100000.0,150000.0,1,1,(52.5 x 37.2 cm.),5-Nov-13,2013 | LIVE AUCTION 3443\nA DIALOGUE THROUGH A...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.00,60000.0,80000.0,1,1,(30.5 x 30.5 cm.),16-May-19,2019 | LIVE AUCTION 16979\nPOST-WAR AND CONTEM...
19,ILSE BING,0,0,"Two street fair views, Paris, 1933",0,USD,2500.00,4000.0,6000.0,1,-1,(28.2 x 19.6 cm.),7-Dec-17,29 Nov - 7 Dec 2017 | Online Auction 15575\nMo...

In [21]:
ArtInfo.shape

(1929, 14)

## spliting the auction titles

In [22]:
Auction_title = []

for items in ArtInfo["Auction Title"]:
    auction_split = items.split("\n")
    Auction_title.append(auction_split[1])

ArtInfo["Auction Title"] = Auction_title

In [23]:
ArtInfo.head(20)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Sold,Est Accuracy,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.00,40000.0,60000.0,1,1,(73 x 54 cm.),17-Nov-16,IMPRESSIONIST & MODERN ART DAY SALE
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,1,(34.6 x 24.7 cm.),18-Dec-17,"The Astor Collection from Tillypronie, Aberdee..."
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,1,(304.8 x 208.2 cm.),16-May-13,POST-WAR & CONTEMPORARY MORNING SESSION
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,1,(66 x 91.4 cm.),13-Dec-12,VICTORIAN & BRITISH IMPRESSIONIST ART
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,1,(35.3 x 27.7cm.),20-Sep-18,First Open Online
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,1,1,(182.9 x 152.4 cm.),27-Sep-18,POST-WAR TO PRESENT
6,JAN DERK HUIBERS,0,0,Cup of warmth,0,USD,7500.00,2500.0,3750.0,1,1,(77.5 x 61.5 cm.),16-Dec-21,British and European Art
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,1,-1,(243.8 x 152.4 cm.),13-May-15,POST-WAR AND CONTEMPORARY ART EVENING SALE
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,1,0,0,4-Dec-13,500 YEARS OF PRINTMAKING
9,WILLIAM EGGLESTON,0,0,"Untitled, 1970s",0,USD,11875.00,12000.0,18000.0,1,-1,(18.4 x 28 cm.),5-Oct-18,PHOTOGRAPHS
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,1,1,(31.1 x 15 cm.),13-Dec-17,VICTORIAN PRE-RAPHAELITE & BRITISH IMPRESSIONI...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,1,0,0,24-Apr-18,POST-WAR AND CONTEMPORARY ART
12,Floris van Schooten,0,0,"Cherries, gooseberries, redcurrants, blackcurr...",0,USD,15750.00,10500.0,15750.0,1,1,0,18-Nov-15,OLD MASTERS & 19TH CENTURYART - (INCLUDING DUT...
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,USD,41895.00,21000.0,31500.0,1,1,0,31-Mar-16,OEUVRES MODERNES SUR PAPIER
14,Lucebert,1924,1994,Untitled,0,USD,7276.50,4200.0,6300.0,1,1,0,26-Apr-22,20th/21st Century: Amsterdam
15,Adam Colonia,Rotterdam,1685,The Annunciation to the Shepherds,0,USD,5250.00,4200.0,6300.0,1,0,0,14-May-14,"OLD MASTERS, 19TH CENTURY AND IMPRESSIONIST ART"
16,Cornelius Jonson van Ceulen and Studio,London,1661,"Portrait of a gentleman, possibly Philip Herbe...",0,USD,4062.50,3750.0,6250.0,1,0,(74.9 x 62.2 cm.),29-Oct-15,OLD MASTER & BRITISH PAINTINGS
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.00,100000.0,150000.0,1,1,(52.5 x 37.2 cm.),5-Nov-13,A DIALOGUE THROUGH ART: WORKS FROM THE JAN KRU...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.00,60000.0,80000.0,1,1,(30.5 x 30.5 cm.),16-May-19,POST-WAR AND CONTEMPORARY ART AFTERNOON SESSION
19,ILSE BING,0,0,"Two street fair views, Paris, 1933",0,USD,2500.00,4000.0,6000.0,1,-1,(28.2 x 19.6 cm.),7-Dec-17,MoMA: Women in Photography

In [24]:
ArtInfo.shape

(1929, 14)

## inconsistancy cleaning: (Not nesesarily bad data but not 100% cleanable)

In [25]:
birth = []
death = []

for b_year, d_year in zip(ArtInfo['Birth'], ArtInfo['Death']):
    try:
        birth.append(int(b_year))
    except:
        birth.append(0)
    try:
        death.append(int(d_year))
    except:
        death.append(-1)

ArtInfo["Birth"] = birth
ArtInfo["Death"] = death

In [26]:
ArtInfo.drop(ArtInfo.index[ArtInfo['Birth'] == 0], inplace=True)
ArtInfo.drop(ArtInfo.index[ArtInfo['Birth'] <= 1500], inplace=True)
ArtInfo.drop(ArtInfo.index[ArtInfo['Death'] == -1], inplace=True)
ArtInfo.drop(ArtInfo.index[ArtInfo['Currency'] != "USD"], inplace=True)

In [27]:
ArtInfo.head(60)

,Artist,Birth,Death,Art Title,DoC,Currency,price,low_estimate,high_estimate,Sold,Est Accuracy,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,Nu,1931,USD,81250.00,40000.0,60000.0,1,1,(73 x 54 cm.),17-Nov-16,IMPRESSIONIST & MODERN ART DAY SALE
1,George Edward Lodge,1860,1954,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,1,(34.6 x 24.7 cm.),18-Dec-17,"The Astor Collection from Tillypronie, Aberdee..."
2,Helen Frankenthaler,1928,2011,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,1,(304.8 x 208.2 cm.),16-May-13,POST-WAR & CONTEMPORARY MORNING SESSION
3,Sir John Alfred Arnesby Brown,1866,1955,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,1,(66 x 91.4 cm.),13-Dec-12,VICTORIAN & BRITISH IMPRESSIONIST ART
4,Raymond Pettibon,1957,0,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,1,(35.3 x 27.7cm.),20-Sep-18,First Open Online
5,Keltie Ferris,1977,0,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,1,1,(182.9 x 152.4 cm.),27-Sep-18,POST-WAR TO PRESENT
7,Robert Rauschenberg,1925,2008,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,1,-1,(243.8 x 152.4 cm.),13-May-15,POST-WAR AND CONTEMPORARY ART EVENING SALE
8,Rembrandt Harmensz. van Rijn,1606,1669,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,1,0,0,4-Dec-13,500 YEARS OF PRINTMAKING
10,"George Howard, 9th Earl of Carlisle",1843,1911,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,1,1,(31.1 x 15 cm.),13-Dec-17,VICTORIAN PRE-RAPHAELITE & BRITISH IMPRESSIONI...
11,Karel Appel,1921,2006,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,1,0,0,24-Apr-18,POST-WAR AND CONTEMPORARY ART
13,Alberto Giacometti,1901,1966,Femme assise et verre à pied,0,USD,41895.00,21000.0,31500.0,1,1,0,31-Mar-16,OEUVRES MODERNES SUR PAPIER
14,Lucebert,1924,1994,Untitled,0,USD,7276.50,4200.0,6300.0,1,1,0,26-Apr-22,20th/21st Century: Amsterdam
17,Odilon Redon,1840,1916,Visage-Germination,1888,USD,233000.00,100000.0,150000.0,1,1,(52.5 x 37.2 cm.),5-Nov-13,A DIALOGUE THROUGH ART: WORKS FROM THE JAN KRU...
18,Jack Whitten,1939,2018,Virgin Space Loop #19,2012,USD,87500.00,60000.0,80000.0,1,1,(30.5 x 30.5 cm.),16-May-19,POST-WAR AND CONTEMPORARY ART AFTERNOON SESSION
20,Nicolas Party,1980,0,Still Life No 103,2012,USD,10625.00,2500.0,3750.0,1,1,(16.5 x 22.2cm.),28-Jun-18,POST-WAR TO PRESENT
21,Samuel Holburn Fyfe,1822,1905,The clipper John R. Worcester outward-bound fr...,0,USD,3906.25,3125.0,4375.0,1,0,(71 x 111.8 cm.),5-Jun-14,MARITIME ART
23,Pedro Friedeberg,1936,0,Pair of Hand Chairs,0,USD,18750.00,15000.0,20000.0,1,0,(86.4 x 48.3 x 50.8 cm.),30-May-18,Latin American Art Online
24,Gunther Gerzso,1915,2000,Trópico calizo,1992,USD,137500.00,70000.0,90000.0,1,1,(81.3 x 100.3 cm.),30-Jul-20,LATIN AMERICAN ART
25,BRASSAÏ,1899,1950,"Graffiti (Serie IV, Masques et Visages), 1935-...",0,USD,18750.00,10000.0,15000.0,1,1,(40 x 30.4 cm.),14-Oct-20,The Unseen Eye: Photographs from the W.M. Hunt...
26,ANDY WARHOL,1928,1987,Marilyn Monroe (Marilyn): one print,0,USD,187500.00,100000.0,150000.0,1,1,(914 x 914 mm.),22-Oct-21,PRINTS & MULTIPLES
27,ARMAN,1928,2005,Sans titre,0,USD,787.50,1260.0,1890.0,1,-1,(13 5/8 x 21¼ in.),26-Oct-13,"DAGNY ET JAN RUNNQVIST, GALERIE BONNIER, UN DE..."
28,ANDY WARHOL,1928,1987,Marilyn Monroe (Marilyn): one print,0,USD,100000.00,80000.0,120000.0,1,0,(914 x 914 mm.),23-Oct-19,PRINTS & MULTIPLES
29,Pablo Picasso,1881,1973,Verve,0,USD,68750.00,30000.0,50000.0,1,1,(35.6 x 26.5 cm.),16-May-18,IMPRESSIONIST AND MODERN ART WORKS ON PAPER
30,Walter Leblanc,1932,1986,Twisted Strings TX. 171,1971,USD,87937.50,73500.0,94500.0,1,0,0,1-May-19,POST-WAR & CONTEMPORARY ART
31,Bernard Buffet,1928,1999,Compotier sur un plateau,1991,USD,91562.50,75000.0,100000.0,1,0,(73 x 92 cm.),21-Jun-12,IMPRESSIONIST/MODERN DAY SALE
32,Jean Paul Riopelle,1923,2002,P.M.12,1960,USD,595350.00,52500.0,73500.0,1,1,0,13-Apr-22,COLLECTION JACQUELINE MATISSE MONNIER
33,Gavin Turk,1967,0,Cave,1997,USD,62500.00,50000.0,75000.0,1,0,(on the reverse),30-Jun-16,POST-WAR AND CONTEMPORARY ART DAY AUCTION
37,Paul Cezanne,1839,1906,Autoportrait,0,USD,1718.75,1500.0,2250.0,1,0,(and similar),4-Dec-14,PRINTS & MULTIPLES
38,Tom Wesselmann,1931,2004,Monica with Wesselmann,1992,USD,234375.00,150000.0,225000.0,1,1,(162.5 x 122.5cm.),7-Oct-17,POST-WAR AND CONTEMPORARY ART DAY AUCTION
39,D'APRES PIET MONDRIAN,1872,1944,Mondrian,0,USD,6562.50,5250.0,7350.0,1,0,0,9-Jun-20,Collection Greta Stroeh : Hommage à Arp
40,Amédée Marcel-Clément,1873,0,Moonlit vessels off the coast,0,USD,6250.00,2500.0,3125.0,1,1,(50.3 x 61 cm.),2-May-14,19TH CENTURY EUROPEAN ART
41,Andy Warhol,1928,1987,Knives,1981,USD,3015000.00,1600000.0,2000000.0,1,1,(228.6 x 177.8 cm.),14-Nov-19,POST-WAR AND CONTEMPORARY ART MORNING SESSION
43,Francis Bacon,1909,1992,Two Men Working in a Field,1971,USD,13403125.00,8750000.0,12500000.0,1,1,(198 x 147cm.),30-Jun-15,POST-WAR AND CONTEMPORARY ART EVENING AUCTION
44,Lynn Chadwick,1914,2003,Sitting Figures on Stripes,0,USD,5000.00,1875.0,3125.0,1,1,(19 x 28.2 cm.),11-Jul-13,MODERN BRITISH ART DAY SALE
46,Giorgio de Chirico,1888,1978,i) Il primo a traversarlo fu l'Ippogrifo quand...,0,USD,15625.00,15000.0,22500.0,1,0,(21 x 15.5 cm.),6-Feb-20,IMPRESSIONIST AND MODERN WORKS ON PAPER
47,Emil Nolde,1867,1956,Porträt eines Mädchens (schwarzes Haar),0,USD,200000.00,80000.0,120000.0,1,1,(47.1 x 36 cm.),12-Nov-18,IMPRESSIONIST AND MODERN ART WORKS ON PAPER
49,Alighiero Boetti,1940,1994,Mappa,1990,USD,2167500.00,800000.0,1200000.0,1,1,(120.5 x 224.8 cm.),15-Nov-16,POST-WAR & CONTEMPORARY ART EVENING SALE
50,Alberto Giacometti,1901,1966,Portrait de Soshana,1958,USD,46875.00,25000.0,37500.0,1,1,(51.2 x 32.8 cm.),23-Jun-16,IMPRESSIONIST & MODERN ART WORKS ON PAPER
52,"J. CHILD, CIRCA 1810",1759,1806,"Bust of William Pitt the Younger (1759-1806), ...",0,USD,781.25,1250.0,1875.0,1,-1,(73.2 x 66 cm.),21-Sep-21,Jasper Conran: The Collection Part II
54,Wifredo Lam,1902,1982,Untitled (Personnages),1958,USD,43750.00,25000.0,30000.0,1,1,(58.4 x 90 cm.),21-Nov-19,LATIN AMERICAN ART
55,HOWARD HODGKIN,1932,2016,As you'd been wont - Wantonly Wantonly Eros Pa...,0,USD,1562.50,1250.0,1875.0,1,0,0,26-Sep-18,Contemporary Edition
56,Andy Warhol,1928,1987,Flowers,1964,USD,8411750.00,6000000.0,9000000.0,1,0,(60.9 x 60.9 cm.),15-May-13,POST-WAR & CONTEMPORARY EVENING SALE
57,Georges Braque,1882,1963,L'aquarium bleu,1960,USD,725000.00,300000.0,400000.0,1,1,(76.5 x 106.4 cm.),15-May-15,IMPRESSIONIST AND MODERN DAY SALE INCLUDING PR...
58,Juan Gris,1887,1927,La Conferencia,1908,USD,336500.00,40000.0,60000.0,1,1,(45 x 31.5 cm.),10-May-18,THE COLLECTION OF PEGGY AND DAVID ROCKEFELLER:...
60,Henry Moore,1898,1986,Apple Orchard in Winter,1977,USD,32500.00,15000.0,20000.0,1,1,(21.9 x 28.2 cm.),13-May-16,IMPRESSIONIST & MODERN ART WORKS ON PAPER
61,Paul Delvaux,1897,1994,Les Trois femmes,1967,USD,15750.00,15750.0,21000.0,1,-1,0,28-Mar-19,"OEUVRES MODERNES SUR PAPIER, INCLUANT DES OEUV..."
63,Christo,1935,2020,"The Pont Neuf, Wrapped (Project for Paris)",1985,USD,183750.00,84000.0,126000.0,1,1,(i),3-Jun-21,POST WAR & CONTEMPORARY ART
69,Sam Francis,1923,1994,Untitled,1969,USD,32500.00,30000.0,40000.0,1,0,(104.7 x 74.9 cm.),4-Mar-16,FIRST OPEN | POST-WAR AND CONTEMPORARY ART
70,Richard Caldicott,1962,0,Untitled #61,1998,USD,10156.25,1875.0,3125.0,1,1,(127 x 101.6cm.),15-Mar-19,The George Michael Collection Online Auction
72,Wolf Kahn,1927,0,Sauna Hut,1989,USD,6250.00,6000.0,8000.0,1,0,(56.5 x 75.6 cm.),22-May-18,American Art Online
74,Tony Cragg,1949,0,Points of View,0,USD,111562.50,84000.0,126000.0,1,0,0,26-Nov-20,Post-War & Contemporary Art Online
75,Hendrik Willem Mesdag,1831,1915,Bomschuiten in the surf near the coast of Sche...,1870,USD,51450.00,42000.0,63000.0,1,0,0,5-Jun-12,IMPRESSIONIST AND MODERN ART
76,Léonard Tsuguharu Foujita,1886,1968,Portrait présumé de Jean Cocteau,1916,USD,7875.00,6300.0,8400.0,1,0,0,31-Mar-16,OEUVRES MODERNES SUR PAPIER
79,LUCIO FONTANA,1899,1968,"Concetto spaziale, Natura",0,USD,127575.00,52500.0,73500.0,1,1,(10 5/8 x 8 5/8 x 9 7/8 in.),5-Jun-13,ART CONTEMPORAIN
80,Jeffrey Steele,1931,0,Lolovo,1964,USD,17968.75,10000.0,15000.0,1,1,(30.5 x 40.7 cm.),20-Nov-18,MODERN BRITISH ART DAY SALE
82,Beauford Delaney,1901,1979,Abstraction No. 4,0,USD,387000.00,100000.0,150000.0,1,1,(129.5 x 96.8 cm.),28-Feb-19,POST-WAR TO PRESENT
83,Henry Moore,1898,1986,Seated Figures (recto and verso),1950,USD,75000.00,50000.0,70000.0,1,1,(29 x 23.6 cm.),14-Nov-17,IMPRESSIONIST AND MODERN ART WORKS ON PAPER SALE
85,Diego Rivera,1886,1957,Niña con flores amarillas,1950,USD,106250.00,60000.0,80000.0,1,1,(38.7 x 27.9 cm.),21-Nov-18,LATIN AMERICAN ART
87,Albert Lebourg,1849,1928,La Mère et l'enfant sur un banc,0,USD,5250.00,2100.0,3150.0,1,1,0,18-Oct-19,ART MODERNE
89,YVES SAINT LAURENT,1936,2008,Untitled,0,USD,75000.00,3750.0,5000.0,1,1,(27.1 x 21.4cm.),19-Oct-21,First Open: Post-War & Contemporary Art Online

In [28]:
ArtInfo.shape

(1197, 14)

In [29]:
ArtInfo.to_csv("Christies_Art_Objects_Clean.csv", index = False)

## Artist Age

In [30]:
Age = []
Alive = []
ADS = []

for b_year, d_year, s_year in zip(ArtInfo['Birth'], ArtInfo['Death'], ArtInfo['close date']):
    
    s_year = s_year[-2:]
    #print(s_year)
    if d_year == 0:
        Current_Age = 2022 - b_year
        Alive.append(1)
        Age.append(Current_Age)
        ADS.append(1)
    else:
        Age_at_death = d_year - b_year
        Alive.append(0)
        Age.append(Age_at_death)
        if Age_at_death > (int(s_year) - b_year):
            ADS.append(1)
        else:
            ADS.append(0)
            
ArtInfo.insert(loc=3, column='Age', value=Age)
ArtInfo.insert(loc=4, column='Alive?', value=Alive)
ArtInfo.drop(ArtInfo.index[ArtInfo['Age'] > 100], inplace=True)
ArtInfo.drop(ArtInfo.index[ArtInfo['Age'] < 10], inplace=True)

In [31]:
ArtInfo.sort_values('price', ascending=False).head(50)
ArtInfo.head(1580)

,Artist,Birth,Death,Age,Alive?,Art Title,DoC,Currency,price,low_estimate,high_estimate,Sold,Est Accuracy,Dimentions,close date,Auction Title
0,Moise Kisling,1891,1953,62,0,Nu,1931,USD,81250.00,40000.0,60000.0,1,1,(73 x 54 cm.),17-Nov-16,IMPRESSIONIST & MODERN ART DAY SALE
1,George Edward Lodge,1860,1954,94,0,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,1,(34.6 x 24.7 cm.),18-Dec-17,"The Astor Collection from Tillypronie, Aberdee..."
2,Helen Frankenthaler,1928,2011,83,0,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,1,(304.8 x 208.2 cm.),16-May-13,POST-WAR & CONTEMPORARY MORNING SESSION
3,Sir John Alfred Arnesby Brown,1866,1955,89,0,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,1,(66 x 91.4 cm.),13-Dec-12,VICTORIAN & BRITISH IMPRESSIONIST ART
4,Raymond Pettibon,1957,0,65,1,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,1,(35.3 x 27.7cm.),20-Sep-18,First Open Online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920,Walter Richard Sickert,1860,1942,82,0,"The Façade of St. Mark's, Venice",0,USD,25000.00,25000.0,37500.0,1,-1,(15.5 x 24.1 cm.),13-Dec-12,MODERN BRITISH AND IRISH ART DAY SALE
1921,Robert Delaunay,1885,1941,56,0,Manège de cochons,1922,USD,651000.00,525000.0,840000.0,1,0,0,14-Apr-21,OEUVRES MODERNES SUR PAPIER / ART IMPRESSIONNI...
1922,Henry Moore,1898,1986,88,0,Two Piece Reclining Figure: Armless,1975,USD,985937.50,625000.0,875000.0,1,1,0,27-Feb-18,IMPRESSIONIST AND MODERN ART EVENING SALE
1924,Walter Gay,1856,1937,81,0,Intérieur Parisien,0,USD,8125.00,4000.0,6000.0,1,1,(55.6 x 45.9 cm.),20-Nov-18,American Art Online
1925,"MITELLI, Giuseppe Maria",1634,1718,84,0,NaN,0,USD,17187.50,2500.0,3750.0,1,1,(365 x 248mm to 403 x 277mm),15-Oct-19,THE ROYAL HOUSE OF SAVOY

In [32]:
ArtInfo.shape

(1187, 16)

## cleaning names:

In [33]:
Artist_Name_lower = []

for artist_name in ArtInfo["Artist"]:
    try:
        Artist = artist_name.lower()
        Artist_Name_lower.append(Artist)
    except:
        Artist_Name_lower.append("0")

        
print(Artist_Name_lower)
ArtInfo['Artist'] = Artist_Name_lower
ArtInfo.drop(ArtInfo.index[ArtInfo['Artist'] == "0"], inplace=True)

['moise kisling ', 'george edward lodge ', 'helen frankenthaler ', 'sir john alfred arnesby brown', 'raymond pettibon ', 'keltie ferris ', 'robert rauschenberg ', 'rembrandt harmensz. van rijn ', 'george howard, 9th earl of carlisle ', 'karel appel ', 'alberto giacometti ', 'lucebert ', 'odilon redon ', 'jack whitten ', 'nicolas party ', 'samuel holburn fyfe ', 'pedro friedeberg ', 'gunther gerzso ', 'brassaï ', 'andy warhol ', 'arman ', 'andy warhol ', 'pablo picasso ', 'walter leblanc ', 'bernard buffet ', 'jean paul riopelle ', 'gavin turk ', 'paul cezanne ', 'tom wesselmann ', "d'apres piet mondrian ", 'andy warhol ', 'francis bacon ', 'lynn chadwick', 'giorgio de chirico ', 'emil nolde ', 'alighiero boetti ', 'alberto giacometti ', 'j. child, circa 1810', 'wifredo lam ', 'howard hodgkin ', 'andy warhol ', 'georges braque ', 'juan gris ', 'henry moore ', 'paul delvaux ', 'christo ', 'sam francis ', 'richard caldicott ', 'wolf kahn ', 'tony cragg ', 'hendrik willem mesdag ', 'léonard tsuguharu foujita ', 'lucio fontana ', 'jeffrey steele ', 'beauford delaney ', 'henry moore ', 'diego rivera ', 'albert lebourg ', 'yves saint laurent ', 'francisco zúñiga ', 'patrick heron ', 'sir peter blake', 'moise kisling ', 'robert motherwell ', 'erich heckel ', 'joseph cornell ', 'henri matisse ', 'eric manigaud ', 'pablo picasso ', 'fernand léger ', 'magdalena abakanowicz ', 'pablo picasso ', 'adam mcewen ', 'gerald leslie brockhurst ', 'mary fedden', 'alighiero boetti ', 'francisco de goya y lucientes ', 'gunther gerzso ', 'zygmund menkes ', 'michelangelo pistoletto ', 'peter alma ', 'louis roy ', 'george grosz ', 'sanyu ', 'andré lhote ', 'grayson perry ', 'max ernst ', 'stanhope alexander forbes, n.e.a.c. ', 'daan van golden ', 'rufino tamayo ', 'laurence stephen lowry', 'graham bell ', 'william scott', 'shara hughes ', 'günther förg ', 'james mcneill whistler ', 'inez van lamsweerde  and vinoodh matadin ', 'samuel john lamorna birch ', 'sir william russell flint. ', 'bob thompson ', 'archibald thorburn ', 'pablo picasso ', 'amy sillman ', 'raoul dufy ', 'lucio fontana ', 'tom wesselmann ', 'rembrandt harmensz. van rijn ', 'francis bacon ', 'marc chagall ', 'raymond hains ', "d'après alexander calder ", 'joseph christian leyendecker ', 'sol lewitt ', 'richard diebenkorn ', 'jean dubuffet ', 'thomas downing ', 'giorgio de chirico ', 'nigel cooke ', 'andre derain ', 'martin kippenberger  & albert oehlen ', 'pablo picasso ', 'philibert cockx ', 'salvador dali ', 'pablo picasso ', 'armand guillaumin ', 'keith haring ', 'mary bauermeister ', 'sir william orpen, r.h.a. ', 'simon hantai ', 'jack lorimer gray ', 'robert william wood ', 'jorge jiménez deredia ', 'edward wadsworth', 'rudolf stingel ', 'gerard curtis delano ', 'fausto melotti ', 'michelangelo pistoletto ', 'francis bacon ', 'georges rouault ', 'andré derain ', 'joan miro ', 'alex katz ', 'ed ruscha ', 'manolo millares ', 'winslow homer ', 'irving penn ', 'gerald laing ', 'günther förg ', 'georges braque ', 'kenneth armitage', 'camille pissarro ', 'jackson pollock ', 'pablo picasso ', 'maximilien luce ', 'eugène dodeigne ', 'gustave loiseau ', 'george grosz ', 'pablo picasso ', 'alan uglow ', 'jan sluijters ', 'emil nolde ', 'eduardo chillida ', 'prunella clough ', 'pablo picasso ', 'jan voerman ', 'ernest lawson ', 'kazuo shiraga ', 'guillermo kuitca ', 'pablo picasso ', 'antonio saura ', 'francis joseph bruguiere ', 'man ray ', 'andy warhol ', 'albert lebourg ', 'victor pasmore', 'pablo picasso ', 'edgar degas ', 'william aiken walker ', 'michel parmentier ', 'katherine bradford ', 'theodoros stamos ', 'henri matisse ', 'howard hodgkin ', 'quirijn van tiel ', 'zoran antonio music ', 'imi knoebel ', 'cecily brown ', 'joan miró ', 'michael raedecker ', 'shio kusaka ', 'samuel john lamorna birch ', 'andrew wyeth ', 'jean fautrier ', 'sir matthew smith ', 'andré derain ', 'irving penn ', 'ellsworth kelly ', 'lucio fontana ', 'elisa sighicelli ', 'utagawa hiroshige ', 'jean dubuffet ', 'edward simmons ', 'marc chagall ', 'massimo vitali ', 'jean fautrier ', 'james ensor ', 'agostino bonalumi ', 'cy twombly ', 'alfred fontville de bréanski ', 'piero dorazio ', 'renato meziat ', 'per kirkeby ', 'eugène boudin ', 'andy warhol ', 'anne estelle rice ', 'henry taylor ', 'james ensor ', 'diane arbus ', 'pablo picasso ', 'johannes theodorus toorop ', 'bochius, joannes', 'lucio fontana ', 'bernard buffet ', 'günther förg ', 'stuart davis ', 'joan miró ', 'willem hussem ', 'horatio henry couldery ', 'alexander calder ', 'marc chagall ', 'émile bernard ', 'clarence holbrook carter ', 'andy warhol ', 'frederic remington ', 'clyde aspevig ', 'a. r. penck ', 'robert therrien ', 'ernst ludwig kirchner ', 'george willem opdenhoff ', 'pierre alechinsky ', 'albert lebourg ', 'john byam liston shaw, a.r.w.s. ', 'conrad felixmüller ', 'hanne darboven ', 'pablo picasso ', 'joan miró ', 'graham sutherland ', 'cy twombly ', 'george grongnet de vassé ', 'mario schifano ', 'geoffrey dashwood ', 'cy twombly ', 'yigal ozeri ', 'ernst ludwig kirchner ', 'günther förg ', 'john marin ', 'john frederick lewis ', 'joan miró ', 'sonia delaunay ', 'giorgio morandi ', 'kenneth noland ', 'eugène boudin ', 'george grosz ', 'josef albers ', 'herb ritts ', 'ernst wilhelm nay ', 'bernard buffet ', 'john roddam spencer stanhope ', 'larry rivers ', 'bernard buffet ', 'keith vaughan ', 'kees van dongen ', 'pablo picasso ', 'george shalders ', 'christopher williams ', 'eugène berman ', 'guo jin ', 'herb ritts ', 'keith haring ', 'kees van dongen ', 'joan miro ', 'alfred sisley ', 'keith vaughan ', 'alfred kubin ', 'claude monet ', 'ferdinand hodler ', 'camille claudel ', 'nicolas party ', 'henri matisse ', 'jan toorop ', 'eliot hodgkin ', 'martin disler ', 'henri martin ', 'henri matisse ', 'oscar edmund berninghaus ', 'yves klein ', 'pablo picasso ', 'franco angeli ', 'albert joseph moore, a.r.w.s. ', 'lucio fontana ', 'howard hodgkin ', 'marc chagall ', 'harold frank wallace ', 'ernst ludwig kirchner ', 'ernst samuel geiger ', 'jasper johns ', 'henry moore ', 'roy lichtenstein ', 'pablo picasso ', 'karel appel ', 'rené daniëls ', 'kees verwey ', 'pablo picasso ', 'maurice utrillo ', 'colin w. burns ', 'william joseph julius caesar bond ', 'pablo picasso ', 'elmgreen & dragset ', 'christopher richard wynne nevinson', 'werner drewes ', 'bernard buffet ', 'john bock ', 'helmut newton ', 'john ford clymer ', 'archibald thorburn ', 'michael kirkham ', 'rené magritte ', 'gary hume ', 'barry mcgee ', 'joan miró ', 'mimi parent ', 'aristide maillol ', 'ansel adams ', 'max beckmann ', 'elizabeth rossetti, née siddal ', 'yoshitomo nara ', 'marc chagall ', 'richard mortenssen ', 'leonor fini ', 'jonas lie ', 'joseph edward southall, r.b.s.a., n.e.a.c. ', 'francis picabia ', 'david hockney ', 'ernie barnes ', 'fernand léger ', 'george turner ', 'andré brasilier ', 'richard diebenkorn ', 'patrick caulfield', 'richard diebenkorn ', 'julia chiang ', 'wilfred gabriel de glehn, n.e.a.c. ', 'salvador dalí ', 'peter lindbergh ', 'paul klee ', 'marc chagall ', 'pablo picasso ', 'norman rockwell ', 'sophie anderson ', 'mimmo rotella ', 'karel appel ', 'pierre bonnard ', 'sean scully ', 'robert indiana ', 'sam moyer ', 'a.r. penck ', 'rembrandt harmensz. van rijn ', 'james smetham ', 'rené burri ', 'pablo gargallo ', 'richard diebenkorn ', 'raoul de keyser ', 'georges rouault ', 'dante gabriel rossetti ', 'sir william blake richmond', 'graciela hasper ', 'giovanni battista piranesi ', 'arago, jacques', 'helen frankenthaler ', 'pablo picasso ', 'sir eduardo paolozzi', 'pablo picasso ', 'andré beaurepaire ', 'christopher wool ', 'giovanni battista piranesi ', 'daan van golden ', 'maqbool fida husain ', 'sir eduardo paolozzi', 'henri lebasque ', 'donald judd ', 'pablo picasso ', 'pablo picasso ', 'pablo picasso ', 'edward weston ', 'william aiken walker ', 'david jagger, r.p. ', 'ben nicholson ', 'sherrie levine ', 'anthony thieme ', 'dame elisabeth frink', 'jean hugo ', 'robert filliou ', 'william herbert dunton ', 'maurice utrillo ', 'joel shapiro ', 'chaïm soutine ', 'rudolf stingel ', 'nathan oliveira ', 'edmund blair leighton ', 'gino severini ', 'pablo picasso ', 'dora maar ', 'terry pope ', 'arthur wardle ', 'francisco de goya y lucientes ', 'howard hodgkin ', 'bruce nauman ', 'hector poleo ', 'louise nevelson ', 'gunther gerzso ', 'edward weston ', 'camille pissarro ', 'joe tilson', 'louis soutter ', 'paul cesar helleu ', 'hans rudolf giger ', 'myles birket foster ', 'harm kamerlingh onnes ', 'ben nicholson ', 'herbert gustave schmalz ', 'parviz tanavoli ', 'frank stella ', 'andy warhol ', 'lyonel feininger ', 'pablo picasso ', 'irving penn ', 'sir william russell flint', 'jean cocteau ', 'louise nevelson ', 'pablo picasso ', 'albert bierstadt ', 'helen frankenthaler ', 'mat collishaw ', 'richard artschwager ', 'tony bevan', 'henri matisse ', 'john rankine barclay ', 'ed ruscha ', 'pablo picasso ', 'jacques villeglé ', 'albert anker ', 'ruth asawa ', 'bill woodrow', 'pablo picasso ', 'sir peter markham scott ', 'henry moore ', 'aristide maillol ', 'ben nicholson ', 'george minne ', 'manolo millares ', 'peter doig ', 'lindsay bernard hall ', 'everett shinn ', 'ken howard', 'emilio sánchez ', 'edward weston ', 'aristide maillol ', 'moïse kisling ', 'julius olsson ', 'marc chagall ', 'karel appel ', 'adriaen jansz. van ostade ', 'david hockney ', 'pablo picasso ', 'yinka shonibare ', 'james seymour ', 'gerhard arij ludwig morgenstjerne munthe ', 'john frederick lewis ', 'francis picabia ', 'jean cocteau ', 'keith haring ', 'joe bradley ', 'charles camoin ', 'paul signac ', 'diane arbus ', 'richard artschwager ', 'william roberts', 'isaac rosenberg ', 'joan miró ', 'günther förg ', 'dylan lewis ', 'wassily kandinsky ', 'nadín ospina ', 'raoul dufy ', 'antony gormley ', 'john chamberlain ', 'william louis sonntag ', 'georges rouault ', 'fred deux ', 'peter sedgley ', 'pablo picasso ', 'frederic, lord leighton. ', 'cy twombly ', 'camille bombois ', 'mathew b. brady ', 'auguste herbin ', 'andré derain ', 'pablo picasso ', 'andy warhol ', 'jacques barraband ', 'archibald thorburn ', 'robert rauschenberg ', 'gerhard richter ', 'pablo picasso ', 'david alfaro siqueiros ', 'salvador dalí ', 'antoni tàpies ', 'yayoi kusama ', 'ben nicholson ', 'pablo picasso ', 'serge poliakoff ', 'brassaï ', 'levi wells prentice ', 'irving penn ', 'willem de kooning ', 'gerhard richter ', 'graham sutherland ', 'dante gabriel rossetti ', 'fred cuming', 'r.b. kitaj', 'graham sutherland, o.m ', 'jorge severino ', 'berlinde de bruyckere ', 'david smith ', 'john graham ', 'sir george frampton', 'rembrandt harmensz. van rijn ', 'sir ernest henry shackleton', 'victor pasmore ', 'gerald cassidy ', 'john emms ', 'pierre bonnard ', 'wolfgang paalen ', 'takashi murakami ', 'dante gabriel rossetti ', 'sir peter blake', 'francisco de goya y lucientes ', 'lucy skaer ', 'jesús rafael soto ', 'richard bosman ', 'edgar degas ', 'marc chagall ', 'william turnbull ', 'joan miró ', 'alan saret ', 'francis bacon ', 'raoul dufy ', 'andy warhol ', 'jean carzou ', 'francis bacon ', 'henri matisse ', 'simeon solomon ', 'henri matisse ', 'igor mitoraj ', 'kees van dongen ', 'pablo picasso ', 'georg baselitz ', 'jim lambie ', 'tom edwin mostyn', 'andré lhote ', 'william marshall brown ', 'john william godward', 'callum innes ', 'marc chagall ', 'pablo picasso ', 'milton avery ', 'gifford beal ', 'arman ', 'sam francis ', 'richard avedon ', 'sol lewitt ', 'arman ', 'auguste rodin ', 'simeon solomon ', 'marino marini ', 'claude monet ', 'a. r. penck ', 'eddie martinez ', 'pablo picasso ', 'pablo picasso ', 'henri matisse ', 'paul cezanne ', 'sigmar polke ', 'emil nolde ', 'andy warhol ', 'arman ', 'egon schiele ', 'lucio fontana ', 'andré masson ', 'guy taplin ', 'antonio saura ', 'eugène zak ', 'gerhard richter ', 'cyrus edwin dallin ', 'wilfrid gabriel de glehn', 'alexander calder ', 'thomas hart benton ', 'pablo picasso ', 'jean dubuffet ', 'victor brauner ', 'allen jones ', 'rembrandt harmensz. van rijn ', 'rené magritte ', 'sigmar polke ', 'kees van bohemen ', 'claude monet ', 'michael ayrton ', 'louis david saugy ', 'niki de saint phalle ', 'gerhard richter ', 'marcel duchamp ', 'mark grotjahn ', 'edward william cooke', 'pablo picasso ', 'henry taylor ', 'georges hugnet ', 'stephan balkenhol ', 'damien hirst ', 'albert marquet ', 'paul klee ', 'arnulf rainer ', 'sir alfred james munnings. ', 'maria spartali stillman ', 'kurt schwitters ', 'pablo picasso ', 'giulio paolini ', 'guy bardone ', 'pablo picasso ', 'eddie martinez ', 'max beckmann ', 'marc chagall ', 'andré derain ', 'joan mitchell ', 'andy warhol ', 'henri matisse ', 'maurice braun ', 'henry thomas alken ', 'paul jacoulet ', 'louis h. grimshaw ', 'pablo picasso ', 'pablo picasso ', 'yayoi kusama ', 'fernand léger ', 'tamuna sirbiladze ', 'archibald thorburn ', 'henri matisse ', 'rob van koningsbruggen ', 'tamuna sirbiladze ', 'heinz mack ', 'antonius höckelmann ', 'pablo picasso ', 'robert edward morrison ', 'bridget riley ', 'edward burra ', 'henri martin ', 'darren woodhead ', 'raymond pettibon ', 'alighiero boetti ', 'jasper johns ', 'horace fisher ', 'john cyril harrison ', 'andy warhol ', 'antonio maria zanetti i', 'pablo picasso ', 'peter kuhfeld ', 'rene auberjonois ', 'sam francis ', 'william pope.l ', 'pablo picasso ', 'mariano rodríguez ', 'roger de la fresnaye ', 'julian schnabel ', 'francisco de goya y lucientes ', 'ellsworth kelly ', 'pablo picasso ', 'liu lui ', 'pablo picasso ', 'eero saarinen ', 'pablo picasso ', 'edzard koning ', 'robert rauschenberg ', 'marc chagall ', 'willem de kooning ', 'christopher wilmarth ', 'marcel duchamp ', 'mary mccartney ', 'louis valtat ', 'pablo picasso ', 'odilon redon ', 'manolo millares ', 'john koch ', 'auguste rodin ', 'mimmo rotella ', 'théo van rysselberghe ', 'frederick h. evans (1853-1943', 'maximilien luce ', 'henry mayo bateman ', 'henri matisse ', 'le corbusier ', 'afro ', 'fernand léger ', 'ellsworth kelly ', 'mark shaw ', 'francis picabia ', 'christopher wood ', 'cuno amiet ', 'maynard dixon ', 'fernand léger ', 'karel appel ', 'robert mangold ', 'karl benjamin ', 'lucio fontana ', 'ventura salimbeni ', 'adam fuss ', 'sol lewitt ', 'george elgar hicks ', 'man ray ', 'joan miro ', 'james ensor ', 'christian marclay ', 'paul gauguin ', 'pablo picasso ', 'mariano rodríguez ', 'osvaldo licini ', 'william macdonald ', 'joseph christian leyendecker ', 'pedro friedeberg ', 'camille pissarro ', 'frederick hall ', 'pablo picasso ', 'michael ayrton ', 'gerald leslie brockhurst', 'george edward lodge ', 'gerhard von graevenitz ', 'marino marini ', 'henri martin ', 'andy warhol ', 'keith haring ', 'gerhard richter ', 'eliot hodgkin ', 'andy warhol ', 'sir william hamo thornycroft', 'fritz schwimbeck ', 'pablo picasso ', 'rirkrit tiravanija ', 'walter leblanc ', 'theodoros stamos ', 'otto piene ', 'frans harrewyn', 'willem de kooning ', 'roberto fabelo ', 'félix elie tobeen ', 'takashi murakami ', 'john currin ', 'john frederick herring, snr. ', 'henri martin ', 'mimmo rotella ', 'claude monet ', 'antoni tàpies ', 'tom wesselmann ', 'marc chagall ', 'pablo picasso ', 'alexander calder ', 'mario sironi ', 'william neave parker ', 'isaac brest ', 'max ernst ', 'félix elie tobeen ', 'bruce conner ', 'sir peter markham scott ', 'captain richard aldworth oliver', 'brice marden ', 'paul fordyce maitland ', 'hugues claude pissarro ', 'eugène boudin ', 'andré brasilier ', 'john atkinson grimshaw ', 'auguste rodin ', 'bart van der leck ', 'ed ruscha ', 'david bomberg ', 'richard pettibone ', 'pablo picasso ', 'thomas francis dicksee ', 'philip wilson steer ', 'joseph kosuth ', 'john hoyland', 'edmund gill ', 'fernand léger ', 'paul eluard ', 'henry moore ', 'constantin brancusi ', 'graham sutherland ', 'edouard vuillard ', 'anish kapoor ', 'gino severini ', 'jacques lipchitz ', 'roy lichtenstein ', 'alexander calder ', 'sir peter blake', 'sir edwin henry landseer', 'kazuo shiraga ', 'pablo picasso ', 'fernando botero ', 'henry moore ', 'sam francis ', 'andres serrano ', 'jacques villon ', 'josef sudek ', 'piero dorazio ', 'takashi murakami ', 'marc chagall ', 'pablo picasso ', 'daniel garcía ', 'alastair morton ', 'rashid johnson ', 'ferdinand hodler ', 'thomas baines ', 'andre dunoyer de segonzac ', 'h.c. westermann ', 'john duncan fergusson ', 'rufino tamayo ', 'richard serra ', 'andy warhol ', 'pablo picasso ', 'john william godward', 'giuseppe santomaso ', 'john george brown ', 'ilse bing ', 'kay sage ', 'roger de la fresnaye ', 'henri laurens ', 'richard prince ', 'hodges, william', 'pablo picasso ', 'joan miró ', 'joan mitchell ', 'fernando botero ', 'pablo picasso ', 'tom wesselmann ', 'andy warhol ', 'roger hilton ', 'alberto giacometti ', 'willem de kooning ', 'salvador dalí ', 'jim dine ', 'diego giacometti ', 'hendrik nicolaas werkman ', 'frank stella ', 'richard avedon ', 'pablo picasso ', 'barbara kruger ', 'karel appel ', 'pablo picasso ', 'albert gleizes ', 'lucio fontana ', 'sir eduardo paolozzi', 'alberto morrocco', 'terry winters ', 'andy warhol ', 'matta ', 'marsden hartley ', 'aristide maillol ', 'catherine opie ', 'sir edwin henry landseer', 'odilon redon ', 'fernando de szyszlo ', 'kurt schwitters ', 'joseph beuys ', 'giuseppe uncini ', 'balthus ', 'pablo picasso ', 'max liebermann ', 'terry frost ', 'pierre bonnard ', 'oskar kokoschka ', 'gabriel alix ', 'max ernst ', 'henry moore ', 'alexander calder ', 'victor vasarely ', 'moïse kisling ', 'ernst samuel geiger ', 'george frederick watts', 'pablo picasso ', 'gabriel alix ', 'richard paul lohse ', 'benjamin williams leader', 'sir terry frost', 'pablo picasso ', 'juan munoz ', 'paul klee ', 'ivon hitchens ', 'edward bawden', 'günther förg ', 'laurence stephen lowry', 'gunther gerzso ', 'alexander calder ', 'joan miro ', 'charles demuth ', 'carl grossberg ', 'pablo picasso ', 'christopher wool ', 'sigmar polke ', 'marcel broodthaers ', 'herman de vries ', "alain jacquet  pour l'atelier a", 'enrico castellani ', 'juan munoz ', 'karel appel ', 'brassaï ', 'jirí kolár ', 'edward seago ', 'jan schoonhoven ', 'john stanton ward', 'cy gavin ', 'max bill ', 'alexander calder ', 'ghada amer ', 'michael ayrton ', 'yves klein ', 'diego giacometti ', 'albert gleizes ', 'paul signac ', 'gilbert & george ', 'pablo picasso ', 'matta ', 'bradley biancardi ', 'georges rouault ', 'moïse kisling ', 'raoul ubac ', 'gerhard richter ', 'han snel ', 'georg baselitz ', 'roy lichtenstein ', 'alexander calder ', 'roy lichtenstein ', 'michel journiac ', 'rembrandt harmensz. van rijn ', 'robert nava ', 'pablo picasso ', 'laurence stephen lowry', 'auguste rodin ', 'henri matisse ', 'kaws ', 'raoul dufy ', 'andy warhol ', 'pablo picasso ', 'alexander archipenko ', 'dame elisabeth frink', 'alberto giacometti ', 'asger jorn ', 'silvio mattioli ', 'thomas zipp ', 'laurence stephen lowry', 'william hodges', 'dame elisabeth frink', 'paul klee ', 'tom wesselmann ', 'ross bleckner ', 'ghada amer ', 'emmanuel sougez ', 'diana scultori', 'yves tanguy ', 'pablo picasso ', 'le corbusier ', 'jasper francis cropsey ', 'wassily kandinsky ', 'berenice abbott ', 'sonia delaunay ', 'pablo picasso ', 'peter lanyon ', 'sigmar polke ', 'bernard aubertin ', 'osvaldo licini ', 'andy warhol ', 'pablo picasso ', 'howard hodgkin ', 'walter leblanc ', 'hendrick hondius i', 'henri matisse ', 'sir john everett millais. ', 'sir peter markham scott ', 'fernand léger ', 'juan gris ', 'mary fedden', 'aboudia ', 'jon schueler ', 'pablo picasso ', 'diego rivera ', 'richmond burton ', 'andré lhote ', 'pablo picasso ', 'christian boltanski ', 'norman rockwell ', 'george chinnery ', 'antonio saura ', 'paul gauguin ', 'dennis hopper ', 'howard hodgkin ', 'brassaï ', 'wassily kandinsky ', 'mary corse ', 'gerrit rietveld ', 'dan flavin ', 'mark tobey ', 'sam francis ', 'ray johnson ', 'jörg immendorff ', 'andy warhol ', 'howard hodgkin ', 'louise j. rayner ', 'yves laloy 

In [34]:
ArtInfo.head(10)

,Artist,Birth,Death,Age,Alive?,Art Title,DoC,Currency,price,low_estimate,high_estimate,Sold,Est Accuracy,Dimentions,close date,Auction Title
0,moise kisling,1891,1953,62,0,Nu,1931,USD,81250.00,40000.0,60000.0,1,1,(73 x 54 cm.),17-Nov-16,IMPRESSIONIST & MODERN ART DAY SALE
1,george edward lodge,1860,1954,94,0,Golden eagle on a branch,0,USD,2656.25,1500.0,2250.0,1,1,(34.6 x 24.7 cm.),18-Dec-17,"The Astor Collection from Tillypronie, Aberdee..."
2,helen frankenthaler,1928,2011,83,0,Cinnamon Burn,1968,USD,663750.00,300000.0,500000.0,1,1,(304.8 x 208.2 cm.),16-May-13,POST-WAR & CONTEMPORARY MORNING SESSION
3,sir john alfred arnesby brown,1866,1955,89,0,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,22500.0,1,1,(66 x 91.4 cm.),13-Dec-12,VICTORIAN & BRITISH IMPRESSIONIST ART
4,raymond pettibon,1957,0,65,1,Untitled (But come up),1987,USD,9375.00,3750.0,6250.0,1,1,(35.3 x 27.7cm.),20-Sep-18,First Open Online
5,keltie ferris,1977,0,45,1,Ghost Trees,2018,USD,50000.00,30000.0,50000.0,1,1,(182.9 x 152.4 cm.),27-Sep-18,POST-WAR TO PRESENT
7,robert rauschenberg,1925,2008,83,0,Calendar,1962,USD,2741000.00,3000000.0,5000000.0,1,-1,(243.8 x 152.4 cm.),13-May-15,POST-WAR AND CONTEMPORARY ART EVENING SALE
8,rembrandt harmensz. van rijn,1606,1669,63,0,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,1875.0,1,0,0,4-Dec-13,500 YEARS OF PRINTMAKING
10,"george howard, 9th earl of carlisle",1843,1911,68,0,Study of a standing draped female figure,0,USD,2343.75,1250.0,1875.0,1,1,(31.1 x 15 cm.),13-Dec-17,VICTORIAN PRE-RAPHAELITE & BRITISH IMPRESSIONI...
11,karel appel,1921,2006,85,0,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,168000.0,1,0,0,24-Apr-18,POST-WAR AND CONTEMPORARY ART

## Setting year

In [36]:
#add a column for relative popularity

relPop = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['relPop'] = relPop

#add a column for relative popularity a year before

relPopEarly = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['relPopEarly'] = relPopEarly

#add a column for relative popularity change

relPopChange = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['relPopChange'] = relPopChange

#add a column for close month

closeMonth = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['closeMonth'] = closeMonth

#add a column for close year

closeYear = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['closeYear'] = closeYear

In [38]:
def monthToNumber(month):
    
    month = month.lower()
    if month=="jan":
        return "01"
    if month=="feb":
        return "02"
    if month=="mar":
        return "03"
    if month=="apr":
        return "04"
    if month=="may":
        return "05"
    if month=="jun":
        return "06"
    if month=="jul":
        return "07"
    if month=="aug":
        return "08"
    if month=="sep":
        return "09"
    if month=="oct":
        return "10"
    if month=="nov":
        return "11"
    if month=="dec":
        return "12"
    else:
        return "ERROR"

## STOP

In [41]:
def checkLengthDay(day):
    
    if len(day) == 1:
        return "0" + day
    return day

In [42]:
day = ""
month = ""
splitItems = []

for rowIndex,artistInfo in ArtInfo.iterrows():
    items = artistInfo["close date"]
    print(items)
    if "null:" in items:
        items = items.replace("null: ","")
        splitItems = items.split()
    else:
        splitItems = items.split('-')
    day = checkLengthDay(splitItems[0])
    month = monthToNumber(splitItems[1])
    ArtInfo.at[rowIndex, 'close date'] = day
    ArtInfo.at[rowIndex, 'closeMonth'] = month
    ArtInfo.at[rowIndex, 'closeYear'] = splitItems[2]

17-Nov-16
Day:  17
month:  11
year:  16
18-Dec-17
Day:  18
month:  12
year:  17
16-May-13
Day:  16
month:  05
year:  13
13-Dec-12
Day:  13
month:  12
year:  12
20-Sep-18
Day:  20
month:  09
year:  18
27-Sep-18
Day:  27
month:  09
year:  18
13-May-15
Day:  13
month:  05
year:  15
4-Dec-13
Day:  04
month:  12
year:  13
13-Dec-17
Day:  13
month:  12
year:  17
24-Apr-18
Day:  24
month:  04
year:  18
31-Mar-16
Day:  31
month:  03
year:  16
26-Apr-22
Day:  26
month:  04
year:  22
5-Nov-13
Day:  05
month:  11
year:  13
16-May-19
Day:  16
month:  05
year:  19
28-Jun-18
Day:  28
month:  06
year:  18
5-Jun-14
Day:  05
month:  06
year:  14
30-May-18
Day:  30
month:  05
year:  18
30-Jul-20
Day:  30
month:  07
year:  20
14-Oct-20
Day:  14
month:  10
year:  20
22-Oct-21
Day:  22
month:  10
year:  21
26-Oct-13
Day:  26
month:  10
year:  13
23-Oct-19
Day:  23
month:  10
year:  19
16-May-18
Day:  16
month:  05
year:  18
1-May-19
Day:  01
month:  05
year:  19
21-Jun-12
Day:  21
month:  06
year:  12
13-Apr-22
Day:  13
month:  04
year:  22
30-Jun-16
Day:  30
month:  06
year:  16
4-Dec-14
Day:  04
month:  12
year:  14
7-Oct-17
Day:  07
month:  10
year:  17
9-Jun-20
Day:  09
month:  06
year:  20
14-Nov-19
Day:  14
month:  11
year:  19
30-Jun-15
Day:  30
month:  06
year:  15
11-Jul-13
Day:  11
month:  07
year:  13
6-Feb-20
Day:  06
month:  02
year:  20
12-Nov-18
Day:  12
month:  11
year:  18
15-Nov-16
Day:  15
month:  11
year:  16
23-Jun-16
Day:  23
month:  06
year:  16
21-Sep-21
Day:  21
month:  09
year:  21
21-Nov-19
Day:  21
month:  11
year:  19
26-Sep-18
Day:  26
month:  09
year:  18
15-May-13
Day:  15
month:  05
year:  13
15-May-15
Day:  15
month:  05
year:  15
10-May-18
Day:  10
month:  05
year:  18
13-May-16
Day:  13
month:  05
year:  16
28-Mar-19
Day:  28
month:  03
year:  19
3-Jun-21
Day:  03
month:  06
year:  21
4-Mar-16
Day:  04
month:  03
year:  16
15-Mar-19
Day:  15
month:  03
year:  19
22-May-18
Day:  22
month:  05
year:  18
26-Nov-20
Day:  26
month:  11
year:  20
5-Jun-12
Day:  05
month:  06
year:  12
31-Mar-16
Day:  31
month:  03
year:  16
5-Jun-13
Day:  05
month:  06
year:  13
20-Nov-18
Day:  20
month:  11
year:  18
28-Feb-19
Day:  28
month:  02
year:  19
14-Nov-17
Day:  14
month:  11
year:  17
21-Nov-18
Day:  21
month:  11
year:  18
18-Oct-19
Day:  18
month:  10
year:  19
19-Oct-21
Day:  19
month:  10
year:  21
13-Nov-20
Day:  13
month:  11
year:  20
21-Nov-19
Day:  21
month:  11
year:  19
26-Jun-15
Day:  26
month:  06
year:  15
17-Nov-16
Day:  17
month:  11
year:  16
8-Oct-20
Day:  08
month:  10
year:  20
19-Jun-19
Day:  19
month:  06
year:  19
13-May-14
Day:  13
month:  05
year:  14
17-May-18
Day:  17
month:  05
year:  18
28-May-20
Day:  28
month:  05
year:  20
17-Sep-20
Day:  17
month:  09
year:  20
21-Oct-16
Day:  21
month:  10
year:  16
17-Jul-19
Day:  17
month:  07
year:  19
24-Oct-14
Day:  24
month:  10
year:  14
8-Mar-13
Day:  08
month:  03
year:  13
18-Sep-19
Day:  18
month:  09
year:  19
20-Mar-14
Day:  20
month:  03
year:  14
11-Feb-14
Day:  11
month:  02
year:  14
23-Oct-20
Day:  23
month:  10
year:  20
18-Nov-20
Day:  18
month:  11
year:  20
25-Oct-12
Day:  25
month:  10
year:  12
11-Feb-16
Day:  11
month:  02
year:  16
10-Dec-13
Day:  10
month:  12
year:  13
29-Mar-19
Day:  29
month:  03
year:  19
11-Jun-20
Day:  11
month:  06
year:  20
3-Jun-21
Day:  03
month:  06
year:  21
18-Oct-18
Day:  18
month:  10
year:  18
12-Sep-12
Day:  12
month:  09
year:  12
1-Jul-20
Day:  01
month:  07
year:  20
12-Jul-12
Day:  12
month:  07
year:  12
18-Jun-20
Day:  18
month:  06
year:  20
28-Nov-18
Day:  28
month:  11
year:  18
2-Jul-20
Day:  02
month:  07
year:  20
23-Nov-18
Day:  23
month:  11
year:  18
2-Mar-21
Day:  02
month:  03
year:  21
5-Oct-19
Day:  05
month:  10
year:  19
12-Apr-17
Day:  12
month:  04
year:  17
24-Apr-14
Day:  24
month:  04
year:  14
29-Sep-14
Day:  29
month:  09
year:  14
19-Jun-14
Day:  19
month:  06
year:  14
11-Dec-14
Day:  11
month:  12
year:  14
17-Jul-13
Day:  17
month:  07
year:  13
12-Dec-12
Day:  12
month:  12
year:  12
7-Dec-20
Day:  07
month:  12
year:  20
5-Oct-18
Day:  05
month:  10
year:  18
8-Nov-12
Day:  08
month:  11
year:  12
12-Feb-20
Day:  12
month:  02
year:  20
21-Sep-17
Day:  21
month:  09
year:  17
14-Dec-17
Day:  14
month:  12
year:  17
27-Jun-12
Day:  27
month:  06
year:  12
21-Jun-18
Day:  21
month:  06
year:  18
25-May-21
Day:  25
month:  05
year:  21
8-Dec-20
Day:  08
month:  12
year:  20
21-May-15
Day:  21
month:  05
year:  15
25-Jun-13
Day:  25
month:  06
year:  13
27-Sep-19
Day:  27
month:  09
year:  19
3-Mar-17
Day:  03
month:  03
year:  17
20-Jul-17
Day:  20
month:  07
year:  17
16-Oct-14
Day:  16
month:  10
year:  14
20-Sep-18
Day:  20
month:  09
year:  18
25-Jul-12
Day:  25
month:  07
year:  12
25-Nov-21
Day:  25
month:  11
year:  21
11-Nov-18
Day:  11
month:  11
year:  18
5-Jun-12
Day:  05
month:  06
year:  12
24-Oct-14
Day:  24
month:  10
year:  14
16-May-19
Day:  16
month:  05
year:  19
29-Mar-19
Day:  29
month:  03
year:  19
16-Apr-21
Day:  16
month:  04
year:  21
5-Mar-20
Day:  05
month:  03
year:  20
20-Nov-18
Day:  20
month:  11
year:  18
1-Jun-12
Day:  01
month:  06
year:  12
22-May-19
Day:  22
month:  05
year:  19
20-Nov-18
Day:  20
month:  11
year:  18
28-May-14
Day:  28
month:  05
year:  14
22-Jan-20
Day:  22
month:  01
year:  20
28-Jun-12
Day:  28
month:  06
year:  12
22-May-18
Day:  22
month:  05
year:  18
16-Nov-21
Day:  16
month:  11
year:  21
16-Oct-15
Day:  16
month:  10
year:  15
16-May-19
Day:  16
month:  05
year:  19
21-Jun-18
Day:  21
month:  06
year:  18
24-Mar-15
Day:  24
month:  03
year:  15
28-Oct-15
Day:  28
month:  10
year:  15
25-Nov-21
Day:  25
month:  11
year:  21
25-Nov-21
Day:  25
month:  11
year:  21
20-Oct-21
Day:  20
month:  10
year:  21
22-May-14
Day:  22
month:  05
year:  14
5-Oct-12
Day:  05
month:  10
year:  12
23-Mar-22
Day:  23
month:  03
year:  22
13-Feb-20
Day:  13
month:  02
year:  20
6-Nov-18
Day:  06
month:  11
year:  18
21-Oct-21
Day:  21
month:  10
year:  21
19-Jun-19
Day:  19
month:  06
year:  19
13-May-15
Day:  13
month:  05
year:  15
2-Mar-18
Day:  02
month:  03
year:  18
6-Nov-14
Day:  06
month:  11
year:  14
6-Dec-21
Day:  06
month:  12
year:  21
14-Nov-17
Day:  14
month:  11
year:  17
19-Jun-13
Day:  19
month:  06
year:  13
22-Sep-21
Day:  22
month:  09
year:  21
25-Jul-14
Day:  25
month:  07
year:  14
17-Jun-14
Day:  17
month:  06
year:  14
25-Jun-14
Day:  25
month:  06
year:  14
25-Jun-13
Day:  25
month:  06
year:  13
24-Nov-17
Day:  24
month:  11
year:  17
7-Dec-17
Day:  07
month:  12
year:  17
9-Jun-15
Day:  09
month:  06
year:  15
22-May-19
Day:  22
month:  05
year:  19
4-Dec-12
Day:  04
month:  12
year:  12
18-Jun-20
Day:  18
month:  06
year:  20
1-Mar-17
Day:  01
month:  03
year:  17
26-Jun-13
Day:  26
month:  06
year:  13
20-Nov-15
Day:  20
month:  11
year:  15
10-Nov-17
Day:  10
month:  11
year:  17
17-May-17
Day:  17
month:  05
year:  17
18-Oct-19
Day:  18
month:  10
year:  19
11-Jul-13
Day:  11
month:  07
year:  13
20-Sep-12
Day:  20
month:  09
year:  12
12-Nov-18
Day:  12
month:  11
year:  18
20-Nov-18
Day:  20
month:  11
year:  18
4-Dec-19
Day:  04
month:  12
year:  19
12-Jun-20
Day:  12
month:  06
year:  20
18-Dec-19
Day:  18
month:  12
year:  19
1-Mar-19
Day:  01
month:  03
year:  19
12-Apr-19
Day:  12
month:  04
year:  19
7-Jun-16
Day:  07
month:  06
year:  16
6-May-21
Day:  06
month:  05
year:  21
26-Sep-13
Day:  26
month:  09
year:  13
12-Feb-20
Day:  12
month:  02
year:  20
19-Nov-20
Day:  19
month:  11
year:  20
21-Apr-16
Day:  21
month:  04
year:  16
16-May-19
Day:  16
month:  05
year:  19
20-Jun-13
Day:  20
month:  06
year:  13
18-Nov-21
Day:  18
month:  11
year:  21
29-Oct-14
Day:  29
month:  10
year:  14
16-Oct-13
Day:  16
month:  10
year:  13
11-Nov-21
Day:  11
month:  11
year:  21
1-Jul-14
Day:  01
month:  07
year:  14
13-Nov-14
Day:  13
month:  11
year:  14
10-Feb-21
Day:  10
month:  02
year:  21
18-May-18
Day:  18
month:  05
year:  18
15-Nov-18
Day:  15
month:  11
year:  18
5-Dec-20
Day:  05
month:  12
year:  20
22-Sep-15
Day:  22
month:  09
year:  15
1-Jul-20
Day:  01
month:  07
year:  20
19-Sep-19
Day:  19
month:  09
year:  19
7-Mar-18
Day:  07
month:  03
year:  18
19-Mar-14
Day:  19
month:  03
year:  14
21-Apr-16
Day:  21
month:  04
year:  16
26-Apr-22
Day:  26
month:  04
year:  22
23-Mar-16
Day:  23
month:  03
year:  16
6-May-21
Day:  06
month:  05
year:  21
4-Aug-20
Day:  04
month:  08
year:  20
26-Nov-19
Day:  26
month:  11
year:  19
3-Dec-13
Day:  03
month:  12
year:  13
15-Dec-20
Day:  15
month:  12
year:  20
11-Jul-13
Day:  11
month:  07
year:  13
9-Mar-21
Day:  09
month:  03
year:  21
16-Dec-14
Day:  16
month:  12
year:  14
9-Mar-22
Day:  09
month:  03
year:  22
31-Mar-16
Day:  31
month:  03
year:  16
23-Mar-18
Day:  23
month:  03
year:  18
20-Jun-13
Day:  20
month:  06
year:  13
16-Oct-15
Day:  16
month:  10
year:  15
15-Jul-20
Day:  15
month:  07
year:  20
14-Oct-15
Day:  14
month:  10
year:  15
23-May-13
Day:  23
month:  05
year:  13
6-Feb-20
Day:  06
month:  02
year:  20
13-Dec-16
Day:  13
month:  12
year:  16
13-Mar-13
Day:  13
month:  03
year:  13
22-Jul-15
Day:  22
month:  07
year:  15
1-Mar-18
Day:  01
month:  03
year:  18
23-Mar-18
Day:  23
month:  03
year:  18
19-Nov-14
Day:  19
month:  11
year:  14
22-Sep-20
Day:  22
month:  09
year:  20
21-May-15
Day:  21
month:  05
year:  15
28-Oct-20
Day:  28
month:  10
year:  20
26-Jun-19
Day:  26
month:  06
year:  19
13-Nov-13
Day:  13
month:  11
year:  13
14-Apr-21
Day:  14
month:  04
year:  21
13-Jun-17
Day:  13
month:  06
year:  17
26-Feb-14
Day:  26
month:  02
year:  14
31-Mar-16
Day:  31
month:  03
year:  16
17-Jun-14
Day:  17
month:  06
year:  14
28-Sep-21
Day:  28
month:  09
year:  21
2-Nov-16
Day:  02
month:  11
year:  16
18-Sep-20
Day:  18
month:  09
year:  20
16-Apr-14
Day:  16
month:  04
year:  14
17-Mar-16
Day:  17
month:  03
year:  16
30-Jun-16
Day:  30
month:  06
year:  16
24-Mar-21
Day:  24
month:  03
year:  21
11-Apr-19
Day:  11
month:  04
year:  19
9-Jul-14
Day:  09
month:  07
year:  14
27-Oct-16
Day:  27
month:  10
year:  16
18-Sep-12
Day:  18
month:  09
year:  12
20-Sep-18
Day:  20
month:  09
year:  18
5-Oct-18

Day:  05
month:  10
year:  18
20-Nov-19
Day:  20
month:  11
year:  19
14-Dec-16
Day:  14
month:  12
year:  16
21-Jun-12
Day:  21
month:  06
year:  12
16-Apr-14
Day:  16
month:  04
year:  14
20-May-21
Day:  20
month:  05
year:  21
28-Feb-19
Day:  28
month:  02
year:  19
16-May-18
Day:  16
month:  05
year:  18
5-Feb-14
Day:  05
month:  02
year:  14
27-Sep-16
Day:  27
month:  09
year:  16
10-Nov-17
Day:  10
month:  11
year:  17
18-Jun-20
Day:  18
month:  06
year:  20
17-Nov-16
Day:  17
month:  11
year:  16
12-Dec-13
Day:  12
month:  12
year:  13
1-Mar-17
Day:  01
month:  03
year:  17
16-May-17
Day:  16
month:  05
year:  17
9-Apr-19
Day:  09
month:  04
year:  19
24-Jun-15
Day:  24
month:  06
year:  15
22-Jun-18
Day:  22
month:  06
year:  18
13-Mar-13
Day:  13
month:  03
year:  13
18-Dec-19
Day:  18
month:  12
year:  19
1-Dec-15
Day:  01
month:  12
year:  15
22-Apr-22
Day:  22
month:  04
year:  22
10-Nov-17
Day:  10
month:  11
year:  17
13-Nov-14
Day:  13
month:  11
year:  14
9-May-13
Day:  09
month:  05
year:  13
15-Jul-15
Day:  15
month:  07
year:  15
27-Feb-18
Day:  27
month:  02
year:  18
14-Dec-12
Day:  14
month:  12
year:  12
28-Feb-18
Day:  28
month:  02
year:  18
11-Nov-18
Day:  11
month:  11
year:  18
17-Oct-17
Day:  17
month:  10
year:  17
12-Nov-15
Day:  12
month:  11
year:  15
15-Dec-21
Day:  15
month:  12
year:  21
17-May-18
Day:  17
month:  05
year:  18
29-May-13
Day:  29
month:  05
year:  13
21-Mar-13
Day:  21
month:  03
year:  13
5-Dec-16
Day:  05
month:  12
year:  16
28-Nov-12
Day:  28
month:  11
year:  12
null: 1 Mar 2019
Day:  01
month:  03
year:  2019
28-Nov-12
Day:  28
month:  11
year:  12
17-Oct-15
Day:  17
month:  10
year:  15
20-Apr-18
Day:  20
month:  04
year:  18
10-Feb-21
Day:  10
month:  02
year:  21
13-Dec-17
Day:  13
month:  12
year:  17
16-Oct-15
Day:  16
month:  10
year:  15
28-Sep-21
Day:  28
month:  09
year:  21
7-Feb-13
Day:  07
month:  02
year:  13
18-Dec-17
Day:  18
month:  12
year:  17
5-Feb-14
Day:  05
month:  02
year:  14
30-May-16
Day:  30
month:  05
year:  16
12-Feb-15
Day:  12
month:  02
year:  15
2-Mar-21
Day:  02
month:  03
year:  21
20-Apr-18
Day:  20
month:  04
year:  18
22-Jun-18
Day:  22
month:  06
year:  18
27-May-21
Day:  27
month:  05
year:  21
21-Apr-16
Day:  21
month:  04
year:  16
29-May-13
Day:  29
month:  05
year:  13
3-Dec-13
Day:  03
month:  12
year:  13
24-Oct-14
Day:  24
month:  10
year:  14
23-Mar-16
Day:  23
month:  03
year:  16
19-Jun-14
Day:  19
month:  06
year:  14
17-May-21
Day:  17
month:  05
year:  21
18-Jun-20
Day:  18
month:  06
year:  20
26-Jun-15
Day:  26
month:  06
year:  15
20-Nov-18
Day:  20
month:  11
year:  18
16-May-17
Day:  16
month:  05
year:  17
5-Feb-20
Day:  05
month:  02
year:  20
9-Nov-21
Day:  09
month:  11
year:  21
28-Oct-20
Day:  28
month:  10
year:  20
18-Dec-17
Day:  18
month:  12
year:  17
26-Apr-22
Day:  26
month:  04
year:  22
3-Dec-13
Day:  03
month:  12
year:  13
20-Nov-12
Day:  20
month:  11
year:  12
8-Mar-13
Day:  08
month:  03
year:  13
23-Jun-16
Day:  23
month:  06
year:  16
8-Jun-18
Day:  08
month:  06
year:  18
18-Oct-19
Day:  18
month:  10
year:  19
30-Sep-20
Day:  30
month:  09
year:  20
15-Sep-21
Day:  15
month:  09
year:  21
11-Jul-18
Day:  11
month:  07
year:  18
15-Dec-20
Day:  15
month:  12
year:  20
6-Nov-14
Day:  06
month:  11
year:  14
27-Oct-20
Day:  27
month:  10
year:  20
2-Nov-16
Day:  02
month:  11
year:  16
7-Aug-20
Day:  07
month:  08
year:  20
4-Sep-14
Day:  04
month:  09
year:  14
5-Feb-15
Day:  05
month:  02
year:  15
20-Jun-18
Day:  20
month:  06
year:  18
10-Mar-22
Day:  10
month:  03
year:  22
27-Feb-18
Day:  27
month:  02
year:  18
13-Mar-13
Day:  13
month:  03
year:  13
21-Jun-18
Day:  21
month:  06
year:  18
18-May-18
Day:  18
month:  05
year:  18
22-Jan-20
Day:  22
month:  01
year:  20
17-May-18
Day:  17
month:  05
year:  18
10-Jul-20
Day:  10
month:  07
year:  20
12-Dec-19
Day:  12
month:  12
year:  19
18-Oct-18
Day:  18
month:  10
year:  18
5-Nov-19
Day:  05
month:  11
year:  19
5-Feb-15
Day:  05
month:  02
year:  15
7-Feb-13
Day:  07
month:  02
year:  13
21-Jun-19
Day:  21
month:  06
year:  19
22-May-19
Day:  22
month:  05
year:  19
16-Jun-15
Day:  16
month:  06
year:  15
19-Sep-17
Day:  19
month:  09
year:  17
27-Nov-18
Day:  27
month:  11
year:  18
1-Jul-21
Day:  01
month:  07
year:  21
11-Feb-15
Day:  11
month:  02
year:  15
24-Mar-22
Day:  24
month:  03
year:  22
15-Dec-20
Day:  15
month:  12
year:  20
25-Mar-21
Day:  25
month:  03
year:  21
20-Sep-12
Day:  20
month:  09
year:  12
13-Dec-17
Day:  13
month:  12
year:  17
10-Nov-17
Day:  10
month:  11
year:  17
7-Dec-16
Day:  07
month:  12
year:  16
20-Jul-21
Day:  20
month:  07
year:  21
21-Apr-16
Day:  21
month:  04
year:  16
1-Mar-17
Day:  01
month:  03
year:  17
13-Jul-16
Day:  13
month:  07
year:  16
16-Jun-15
Day:  16
month:  06
year:  15
29-May-19
Day:  29
month:  05
year:  19
28-Jan-21
Day:  28
month:  01
year:  21
29-Oct-19
Day:  29
month:  10
year:  19
27-Sep-19
Day:  27
month:  09
year:  19
13-Nov-19
Day:  13
month:  11
year:  19
23-Mar-22
Day:  23
month:  03
year:  22
13-Nov-19
Day:  13
month:  11
year:  19
6-Apr-22
Day:  06
month:  04
year:  22
17-May-18
Day:  17
month:  05
year:  18
4-Dec-14
Day:  04
month:  12
year:  14
18-Jun-20
Day:  18
month:  06
year:  20
25-May-17
Day:  25
month:  05
year:  17
20-Nov-18
Day:  20
month:  11
year:  18
8-Nov-12
Day:  08
month:  11
year:  12
22-Mar-16
Day:  22
month:  03
year:  16
13-Nov-18
Day:  13
month:  11
year:  18
15-May-19
Day:  15
month:  05
year:  19
2-Mar-18
Day:  02
month:  03
year:  18
31-Mar-15
Day:  31
month:  03
year:  15
25-Mar-15
Day:  25
month:  03
year:  15
29-Sep-20
Day:  29
month:  09
year:  20
21-Oct-21
Day:  21
month:  10
year:  21
27-Sep-13
Day:  27
month:  09
year:  13
22-May-19
Day:  22
month:  05
year:  19
21-Nov-13
Day:  21
month:  11
year:  13
6-Dec-18
Day:  06
month:  12
year:  18
4-Dec-19
Day:  04
month:  12
year:  19
21-Nov-17
Day:  21
month:  11
year:  17
3-Dec-13
Day:  03
month:  12
year:  13
27-Sep-17
Day:  27
month:  09
year:  17
28-Feb-19
Day:  28
month:  02
year:  19
6-Mar-18
Day:  06
month:  03
year:  18
29-Oct-14
Day:  29
month:  10
year:  14
12-Dec-19
Day:  12
month:  12
year:  19
22-Jun-12
Day:  22
month:  06
year:  12
15-Nov-17
Day:  15
month:  11
year:  17
20-Nov-15
Day:  20
month:  11
year:  15
24-Nov-17
Day:  24
month:  11
year:  17
27-Nov-13
Day:  27
month:  11
year:  13
23-Oct-20
Day:  23
month:  10
year:  20
12-Apr-19
Day:  12
month:  04
year:  19
16-May-13
Day:  16
month:  05
year:  13
24-May-18
Day:  24
month:  05
year:  18
22-Jul-15
Day:  22
month:  07
year:  15
18-Feb-22
Day:  18
month:  02
year:  22
13-Nov-14
Day:  13
month:  11
year:  14
15-May-15
Day:  15
month:  05
year:  15
22-Jan-20
Day:  22
month:  01
year:  20
24-Sep-12
Day:  24
month:  09
year:  12
10-Oct-12
Day:  10
month:  10
year:  12
5-May-15
Day:  05
month:  05
year:  15
13-Jul-16
Day:  13
month:  07
year:  16
4-Sep-12
Day:  04
month:  09
year:  12
20-Nov-18
Day:  20
month:  11
year:  18
11-Jul-18
Day:  11
month:  07
year:  18
22-Mar-18
Day:  22
month:  03
year:  18
14-May-14
Day:  14
month:  05
year:  14
12-Feb-20
Day:  12
month:  02
year:  20
10-May-18
Day:  10
month:  05
year:  18
13-Nov-19
Day:  13
month:  11
year:  19
5-Nov-19
Day:  05
month:  11
year:  19
26-Nov-14
Day:  26
month:  11
year:  14
17-Jul-20
Day:  17
month:  07
year:  20
28-Sep-17
Day:  28
month:  09
year:  17
15-May-19
Day:  15
month:  05
year:  19
19-Jan-22
Day:  19
month:  01
year:  22
15-Jul-15
Day:  15
month:  07
year:  15
14-Mar-19
Day:  14
month:  03
year:  19
26-Sep-13
Day:  26
month:  09
year:  13
22-Jan-20
Day:  22
month:  01
year:  20
23-Jun-21
Day:  23
month:  06
year:  21
23-Mar-16
Day:  23
month:  03
year:  16
7-Oct-17
Day:  07
month:  10
year:  17
20-Sep-18
Day:  20
month:  09
year:  18
25-May-21
Day:  25
month:  05
year:  21
18-Sep-18
Day:  18
month:  09
year:  18
12-Nov-21
Day:  12
month:  11
year:  21
23-Mar-17
Day:  23
month:  03
year:  17
18-Nov-21
Day:  18
month:  11
year:  21
10-Dec-14
Day:  10
month:  12
year:  14
27-Jun-17
Day:  27
month:  06
year:  17
28-Mar-19
Day:  28
month:  03
year:  19
20-Nov-14
Day:  20
month:  11
year:  14
6-Feb-20
Day:  06
month:  02
year:  20
2-Jul-14
Day:  02
month:  07
year:  14
8-Mar-13
Day:  08
month:  03
year:  13
24-Sep-15
Day:  24
month:  09
year:  15
18-Nov-21
Day:  18
month:  11
year:  21
23-Mar-17
Day:  23
month:  03
year:  17
26-Nov-19
Day:  26
month:  11
year:  19
14-Nov-13
Day:  14
month:  11
year:  13
7-Feb-13
Day:  07
month:  02
year:  13
14-May-21
Day:  14
month:  05
year:  21
20-Jun-13
Day:  20
month:  06
year:  13
19-Jun-19
Day:  19
month:  06
year:  19
21-Apr-16
Day:  21
month:  04
year:  16
29-Mar-17
Day:  29
month:  03
year:  17
null: 22 Sep 2020
Day:  22
month:  09
year:  2020
15-Nov-17
Day:  15
month:  11
year:  17
8-Mar-13
Day:  08
month:  03
year:  13
27-Jun-12
Day:  27
month:  06
year:  12
12-Mar-13
Day:  12
month:  03
year:  13
14-Dec-16
Day:  14
month:  12
year:  16
13-Dec-16
Day:  13
month:  12
year:  16
25-Oct-12
Day:  25
month:  10
year:  12
13-Feb-20
Day:  13
month:  02
year:  20
27-May-20
Day:  27
month:  05
year:  20
8-Oct-20
Day:  08
month:  10
year:  20
6-Nov-13
Day:  06
month:  11
year:  13
7-Apr-22
Day:  07
month:  04
year:  22
5-Feb-20
Day:  05
month:  02
year:  20
24-Nov-16
Day:  24
month:  11
year:  16
26-Jun-15
Day:  26
month:  06
year:  15
26-Jun-15
Day:  26
month:  06
year:  15
14-Jul-20
Day:  14
month:  07
year:  20
10-Sep-19
Day:  10
month:  09
year:  19
27-Apr-16
Day:  27
month:  04
year:  16
30-May-18
Day:  30
month:  05
year:  18
13-Dec-16
Day:  13
month:  12
year:  16
30-Jun-16
Day:  30
month:  06
year:  16
6-Oct-17
Day:  06
month:  10
year:  17
19-Jan-17
Day:  19
month:  01
year:  17
28-Jun-17
Day:  28
month:  06
year:  17
4-Dec-19
Day:  04
month:  12
year:  19
5-Oct-19
Day:  05
month:  10
year:  19
29-Jun-17
Day:  29
month:  06
year:  17
14-Dec-16
Day:  14
month:  12
year:  16
17-May-17
Day:  17
month:  05
year:  17
5-Feb-16
Day:  05
month:  02
year:  16
7-Oct-21
Day:  07
month:  10

year:  21
8-Feb-13
Day:  08
month:  02
year:  13
13-Nov-21
Day:  13
month:  11
year:  21
20-Jun-19
Day:  20
month:  06
year:  19
17-Oct-17
Day:  17
month:  10
year:  17
14-Dec-17
Day:  14
month:  12
year:  17
9-Jul-14
Day:  09
month:  07
year:  14
14-May-15
Day:  14
month:  05
year:  15
12-Oct-12
Day:  12
month:  10
year:  12
7-Feb-20
Day:  07
month:  02
year:  20
21-Nov-19
Day:  21
month:  11
year:  19
11-Nov-19
Day:  11
month:  11
year:  19
4-Dec-19
Day:  04
month:  12
year:  19
19-Oct-13
Day:  19
month:  10
year:  13
22-Sep-20
Day:  22
month:  09
year:  20
21-Jun-18
Day:  21
month:  06
year:  18
4-Dec-19
Day:  04
month:  12
year:  19
10-Nov-17
Day:  10
month:  11
year:  17
7-Aug-20
Day:  07
month:  08
year:  20
5-Nov-19
Day:  05
month:  11
year:  19
7-Oct-20
Day:  07
month:  10
year:  20
5-Oct-19
Day:  05
month:  10
year:  19
26-Jun-15
Day:  26
month:  06
year:  15
14-Dec-16
Day:  14
month:  12
year:  16
18-Aug-15
Day:  18
month:  08
year:  15
11-Jul-13
Day:  11
month:  07
year:  13
28-Jun-17
Day:  28
month:  06
year:  17
28-Nov-18
Day:  28
month:  11
year:  18
27-Jun-12
Day:  27
month:  06
year:  12
13-May-15
Day:  13
month:  05
year:  15
27-Sep-17
Day:  27
month:  09
year:  17
12-Dec-19
Day:  12
month:  12
year:  19
20-Mar-13
Day:  20
month:  03
year:  13
5-Nov-20
Day:  05
month:  11
year:  20
21-Sep-17
Day:  21
month:  09
year:  17
22-May-14
Day:  22
month:  05
year:  14
27-Jun-12
Day:  27
month:  06
year:  12
22-Mar-17
Day:  22
month:  03
year:  17
30-Mar-22
Day:  30
month:  03
year:  22
21-Apr-22
Day:  21
month:  04
year:  22
11-Dec-18
Day:  11
month:  12
year:  18
26-Jun-15
Day:  26
month:  06
year:  15
23-Oct-20
Day:  23
month:  10
year:  20
20-Nov-12
Day:  20
month:  11
year:  12
24-May-18
Day:  24
month:  05
year:  18
15-Dec-20
Day:  15
month:  12
year:  20
20-Jun-12
Day:  20
month:  06
year:  12
26-Jun-15
Day:  26
month:  06
year:  15
22-Nov-16
Day:  22
month:  11
year:  16
18-Mar-20
Day:  18
month:  03
year:  20
27-Sep-17
Day:  27
month:  09
year:  17
14-May-20
Day:  14
month:  05
year:  20
3-Feb-16
Day:  03
month:  02
year:  16
31-Mar-22
Day:  31
month:  03
year:  22
1-Dec-12
Day:  01
month:  12
year:  12
1-Mar-22
Day:  01
month:  03
year:  22
7-Dec-17
Day:  07
month:  12
year:  17
11-Jul-18
Day:  11
month:  07
year:  18
5-Nov-13
Day:  05
month:  11
year:  13
18-Jun-20
Day:  18
month:  06
year:  20
5-Feb-14
Day:  05
month:  02
year:  14
2-Mar-18
Day:  02
month:  03
year:  18
12-Feb-16
Day:  12
month:  02
year:  16
15-Dec-20
Day:  15
month:  12
year:  20
23-Mar-16
Day:  23
month:  03
year:  16
24-Oct-14
Day:  24
month:  10
year:  14
20-Jun-13
Day:  20
month:  06
year:  13
13-Jul-16
Day:  13
month:  07
year:  16
29-Sep-20
Day:  29
month:  09
year:  20
27-Jun-14
Day:  27
month:  06
year:  14
17-Sep-20
Day:  17
month:  09
year:  20
18-May-21
Day:  18
month:  05
year:  21
22-May-18
Day:  22
month:  05
year:  18
6-Dec-17
Day:  06
month:  12
year:  17
25-Mar-21
Day:  25
month:  03
year:  21
19-Jun-19
Day:  19
month:  06
year:  19
19-Sep-12
Day:  19
month:  09
year:  12
27-Feb-19
Day:  27
month:  02
year:  19
16-May-17
Day:  16
month:  05
year:  17
13-Jul-16
Day:  13
month:  07
year:  16
4-Mar-22
Day:  04
month:  03
year:  22
20-Jun-12
Day:  20
month:  06
year:  12
17-Oct-14
Day:  17
month:  10
year:  14
13-Feb-20
Day:  13
month:  02
year:  20
21-Oct-20
Day:  21
month:  10
year:  20
17-May-21
Day:  17
month:  05
year:  21
22-Oct-20
Day:  22
month:  10
year:  20
25-Jun-14
Day:  25
month:  06
year:  14
13-Dec-17
Day:  13
month:  12
year:  17
7-Feb-13
Day:  07
month:  02
year:  13
21-Jul-21
Day:  21
month:  07
year:  21
6-Dec-17
Day:  06
month:  12
year:  17
7-Feb-13
Day:  07
month:  02
year:  13
3-Dec-21
Day:  03
month:  12
year:  21
8-Feb-13
Day:  08
month:  02
year:  13
27-Jun-12
Day:  27
month:  06
year:  12
4-Jun-15
Day:  04
month:  06
year:  15
28-Feb-19
Day:  28
month:  02
year:  19
12-Oct-12
Day:  12
month:  10
year:  12
7-Aug-20
Day:  07
month:  08
year:  20
3-Dec-15
Day:  03
month:  12
year:  15
15-Nov-16
Day:  15
month:  11
year:  16
21-May-15
Day:  21
month:  05
year:  15
17-Jun-14
Day:  17
month:  06
year:  14
27-Oct-16
Day:  27
month:  10
year:  16
25-Jun-14
Day:  25
month:  06
year:  14
19-Sep-13
Day:  19
month:  09
year:  13
29-Mar-17
Day:  29
month:  03
year:  17
28-Feb-19
Day:  28
month:  02
year:  19
29-Sep-16
Day:  29
month:  09
year:  16
1-Dec-15
Day:  01
month:  12
year:  15
11-Nov-18
Day:  11
month:  11
year:  18
14-Dec-12
Day:  14
month:  12
year:  12
30-May-16
Day:  30
month:  05
year:  16
26-Oct-13
Day:  26
month:  10
year:  13
12-Feb-15
Day:  12
month:  02
year:  15
17-Nov-16
Day:  17
month:  11
year:  16
16-Nov-17
Day:  16
month:  11
year:  17
13-Dec-12
Day:  13
month:  12
year:  12
5-Feb-14
Day:  05
month:  02
year:  14
19-Sep-19
Day:  19
month:  09
year:  19
1-Dec-15
Day:  01
month:  12
year:  15
18-Dec-19
Day:  18
month:  12
year:  19
17-Sep-15
Day:  17
month:  09
year:  15
28-Jun-17
Day:  28
month:  06
year:  17
16-May-18
Day:  16
month:  05
year:  18
25-Nov-21
Day:  25
month:  11
year:  21
12-Mar-15
Day:  12
month:  03
year:  15
17-Jun-14
Day:  17
month:  06
year:  14
14-Nov-17
Day:  14
month:  11
year:  17
20-Jun-19
Day:  20
month:  06
year:  19
21-Apr-16
Day:  21
month:  04
year:  16
28-Aug-13
Day:  28
month:  08
year:  13
20-Oct-21
Day:  20
month:  10
year:  21
18-Aug-20
Day:  18
month:  08
year:  20
20-Sep-18
Day:  20
month:  09
year:  18
6-Nov-13
Day:  06
month:  11
year:  13
11-Nov-19
Day:  11
month:  11
year:  19
17-May-18
Day:  17
month:  05
year:  18
16-Nov-16
Day:  16
month:  11
year:  16
7-May-14
Day:  07
month:  05
year:  14
25-Mar-15
Day:  25
month:  03
year:  15
9-Jul-14
Day:  09
month:  07
year:  14
29-Oct-19
Day:  29
month:  10
year:  19
14-Dec-16
Day:  14
month:  12
year:  16
1-Mar-22
Day:  01
month:  03
year:  22
28-Sep-21
Day:  28
month:  09
year:  21
8-Mar-13
Day:  08
month:  03
year:  13
5-Feb-14
Day:  05
month:  02
year:  14
null: 19 Sep 2019
Day:  19
month:  09
year:  2019
27-Nov-13
Day:  27
month:  11
year:  13
22-Oct-20
Day:  22
month:  10
year:  20
21-Apr-16
Day:  21
month:  04
year:  16
7-Jul-21
Day:  07
month:  07
year:  21
27-Nov-18
Day:  27
month:  11
year:  18
20-Oct-21
Day:  20
month:  10
year:  21
27-Feb-18
Day:  27
month:  02
year:  18
8-Jul-15
Day:  08
month:  07
year:  15
15-Nov-12
Day:  15
month:  11
year:  12
21-Oct-21
Day:  21
month:  10
year:  21
16-May-18
Day:  16
month:  05
year:  18
18-Dec-17
Day:  18
month:  12
year:  17
15-Dec-20
Day:  15
month:  12
year:  20
10-Jun-16
Day:  10
month:  06
year:  16
13-Nov-13
Day:  13
month:  11
year:  13
12-Mar-15
Day:  12
month:  03
year:  15
18-Dec-17
Day:  18
month:  12
year:  17
31-Mar-22
Day:  31
month:  03
year:  22
15-Jul-20
Day:  15
month:  07
year:  20
20-Apr-18
Day:  20
month:  04
year:  18
19-Mar-20
Day:  19
month:  03
year:  20
5-Dec-16
Day:  05
month:  12
year:  16
27-Feb-19
Day:  27
month:  02
year:  19
30-Mar-21
Day:  30
month:  03
year:  21
15-Nov-21
Day:  15
month:  11
year:  21
23-Nov-16
Day:  23
month:  11
year:  16
24-Mar-17
Day:  24
month:  03
year:  17
17-Jul-13
Day:  17
month:  07
year:  13
19-Sep-17
Day:  19
month:  09
year:  17
1-Mar-16
Day:  01
month:  03
year:  16
20-May-20
Day:  20
month:  05
year:  20
24-Oct-14
Day:  24
month:  10
year:  14
20-Apr-18
Day:  20
month:  04
year:  18
13-Feb-18
Day:  13
month:  02
year:  18
1-Mar-22
Day:  01
month:  03
year:  22
12-Mar-13
Day:  12
month:  03
year:  13
19-Jul-17
Day:  19
month:  07
year:  17
22-Sep-20
Day:  22
month:  09
year:  20
21-Jul-21
Day:  21
month:  07
year:  21
27-Sep-17
Day:  27
month:  09
year:  17
18-Oct-18
Day:  18
month:  10
year:  18
15-Mar-19
Day:  15
month:  03
year:  19
29-Mar-19
Day:  29
month:  03
year:  19
29-Oct-14
Day:  29
month:  10
year:  14
5-Apr-17
Day:  05
month:  04
year:  17
7-Mar-18
Day:  07
month:  03
year:  18
18-May-21
Day:  18
month:  05
year:  21
8-Nov-12
Day:  08
month:  11
year:  12
20-Oct-21
Day:  20
month:  10
year:  21
23-Oct-20
Day:  23
month:  10
year:  20
6-Oct-15
Day:  06
month:  10
year:  15
29-Mar-19
Day:  29
month:  03
year:  19
20-Nov-18
Day:  20
month:  11
year:  18
22-Oct-20
Day:  22
month:  10
year:  20
16-May-17
Day:  16
month:  05
year:  17
16-Oct-14
Day:  16
month:  10
year:  14
8-Dec-20
Day:  08
month:  12
year:  20
19-Jul-17
Day:  19
month:  07
year:  17
19-Jun-19
Day:  19
month:  06
year:  19
28-Feb-19
Day:  28
month:  02
year:  19
21-Mar-13
Day:  21
month:  03
year:  13
17-Oct-17
Day:  17
month:  10
year:  17
20-Nov-19
Day:  20
month:  11
year:  19
21-Oct-16
Day:  21
month:  10
year:  16
27-Nov-18
Day:  27
month:  11
year:  18
11-Feb-16
Day:  11
month:  02
year:  16
25-Sep-14
Day:  25
month:  09
year:  14
16-Oct-15
Day:  16
month:  10
year:  15
6-Dec-18
Day:  06
month:  12
year:  18
6-Oct-15
Day:  06
month:  10
year:  15
27-Feb-19
Day:  27
month:  02
year:  19
11-Dec-18
Day:  11
month:  12
year:  18
2-Mar-21
Day:  02
month:  03
year:  21
8-Nov-12
Day:  08
month:  11
year:  12
19-Mar-14
Day:  19
month:  03
year:  14
15-Mar-19
Day:  15
month:  03
year:  19
3-Feb-16
Day:  03
month:  02
year:  16
1-Mar-19
Day:  01
month:  03
year:  19
24-May-18
Day:  24
month:  05
year:  18
5-Nov-20
Day:  05
month:  11
year:  20
4-Sep-14
Day:  04
month:  09
year:  14
21-Nov-17
Day:  21
month:  11
year:  17
27-May-20
Day:  27
month:  05
year:  20
11-Nov-18
Day:  11
month:  11
year:  18
12-Mar-15
Day:  12
month:  03
year:  15
28-Oct-15
Day:  28
month:  10
year:  15
23-Nov-18
Day:  23
month:  11
year:  18
26-Jun-15
Day:  26
month:  06
year:  15
15-Dec-17
Day:  15
month:  12
year:  17
31-Oct-12
Day:  31
month:  10
year:  12
16-Oct-14
Day:  16
month:  10
year:  14
24-Jun-15
Day:  24
month:  06
year:  15
4-Dec-12
Day:  04
month:  12
year:  12
14-May-20
Day:  14
month:  05
year:  20
7-Mar-19
Day:  07
month:  03
year:  19
23-Nov-17
Day:  23
month:  11
year:  17
13-Nov-13
Day:  13
month:  11
year:  13
11-Dec-14
Day:  11
month:  12
year:  14
7-Feb-13
Day:  07
month:  02
year:  13
19-Sep-17
Day:  19
month:  09
year:  17
27-Sep-18
Day:  27
month:  09
year:  18
31-Oct-12
Day:  31
month:  10
year:  12
10-Mar-22
Day:  10
month:  03
year:  22
4-Nov-15
Day:  04
month:  11
year:  15
9-Dec-15
Day:  09
month:  12
year:  15
13-May-14
Day:  13
month:  05
year:  14
18-Feb-22
Day:  18
month:  02
year:  22
27-Nov-12

Day:  27
month:  11
year:  12
16-Nov-17
Day:  16
month:  11
year:  17
18-May-17
Day:  18
month:  05
year:  17
10-Dec-14
Day:  10
month:  12
year:  14
28-Feb-19
Day:  28
month:  02
year:  19
19-Sep-19
Day:  19
month:  09
year:  19
11-Nov-21
Day:  11
month:  11
year:  21
16-May-19
Day:  16
month:  05
year:  19
28-Jun-18
Day:  28
month:  06
year:  18
1-Jul-20
Day:  01
month:  07
year:  20
7-Dec-20
Day:  07
month:  12
year:  20
1-Jul-15
Day:  01
month:  07
year:  15
8-Feb-13
Day:  08
month:  02
year:  13
18-Dec-17
Day:  18
month:  12
year:  17
19-Sep-19
Day:  19
month:  09
year:  19
18-Oct-18
Day:  18
month:  10
year:  18
27-Nov-12
Day:  27
month:  11
year:  12
19-Jul-17
Day:  19
month:  07
year:  17
27-Nov-13
Day:  27
month:  11
year:  13
15-Dec-16
Day:  15
month:  12
year:  16
13-May-14
Day:  13
month:  05
year:  14
26-Nov-14
Day:  26
month:  11
year:  14
28-Aug-13
Day:  28
month:  08
year:  13
26-Nov-17
Day:  26
month:  11
year:  17
1-Mar-17
Day:  01
month:  03
year:  17
13-Jul-16
Day:  13
month:  07
year:  16
11-Nov-18
Day:  11
month:  11
year:  18
12-Mar-13
Day:  12
month:  03
year:  13
14-Nov-19
Day:  14
month:  11
year:  19
13-Dec-12
Day:  13
month:  12
year:  12
16-May-13
Day:  16
month:  05
year:  13
27-Apr-16
Day:  27
month:  04
year:  16
17-Jun-14
Day:  17
month:  06
year:  14
13-Dec-12
Day:  13
month:  12
year:  12
25-Nov-21
Day:  25
month:  11
year:  21
26-Nov-15
Day:  26
month:  11
year:  15
15-Nov-12
Day:  15
month:  11
year:  12
21-Oct-16
Day:  21
month:  10
year:  16
1-Dec-15
Day:  01
month:  12
year:  15
21-Jun-16
Day:  21
month:  06
year:  16
5-Nov-19
Day:  05
month:  11
year:  19
12-Dec-13
Day:  12
month:  12
year:  13
22-Aug-19
Day:  22
month:  08
year:  19
27-Sep-13
Day:  27
month:  09
year:  13
5-Nov-13
Day:  05
month:  11
year:  13
1-Dec-15
Day:  01
month:  12
year:  15
14-Nov-19
Day:  14
month:  11
year:  19
11-Feb-15
Day:  11
month:  02
year:  15
21-Jun-16
Day:  21
month:  06
year:  16
11-Jul-13
Day:  11
month:  07
year:  13
4-Dec-12
Day:  04
month:  12
year:  12
22-Jun-18
Day:  22
month:  06
year:  18
28-May-14
Day:  28
month:  05
year:  14
24-Jun-15
Day:  24
month:  06
year:  15
12-Sep-12
Day:  12
month:  09
year:  12
18-Aug-20
Day:  18
month:  08
year:  20
30-Oct-13
Day:  30
month:  10
year:  13
14-Sep-17
Day:  14
month:  09
year:  17
4-Apr-19
Day:  04
month:  04
year:  19
11-Dec-20
Day:  11
month:  12
year:  20
7-Feb-13
Day:  07
month:  02
year:  13
17-May-21
Day:  17
month:  05
year:  21
29-May-19
Day:  29
month:  05
year:  19
11-Jul-13
Day:  11
month:  07
year:  13
27-Sep-13
Day:  27
month:  09
year:  13
11-Dec-13
Day:  11
month:  12
year:  13
14-Dec-17
Day:  14
month:  12
year:  17
16-May-17
Day:  16
month:  05
year:  17
20-Jul-17
Day:  20
month:  07
year:  17
21-Mar-18
Day:  21
month:  03
year:  18
23-Nov-16
Day:  23
month:  11
year:  16
12-Feb-15
Day:  12
month:  02
year:  15
15-Nov-16
Day:  15
month:  11
year:  16
20-May-20
Day:  20
month:  05
year:  20
12-Dec-19
Day:  12
month:  12
year:  19
4-Dec-19
Day:  04
month:  12
year:  19
20-Nov-18
Day:  20
month:  11
year:  18
13-Nov-14
Day:  13
month:  11
year:  14
5-Feb-15
Day:  05
month:  02
year:  15
15-May-15
Day:  15
month:  05
year:  15
20-Jun-12
Day:  20
month:  06
year:  12
18-May-18
Day:  18
month:  05
year:  18
29-Oct-19
Day:  29
month:  10
year:  19
13-Nov-18
Day:  13
month:  11
year:  18
22-Sep-20
Day:  22
month:  09
year:  20
13-May-14
Day:  13
month:  05
year:  14
28-Feb-19
Day:  28
month:  02
year:  19
28-Nov-12
Day:  28
month:  11
year:  12
26-Sep-18
Day:  26
month:  09
year:  18
23-Oct-19
Day:  23
month:  10
year:  19
11-Jul-13
Day:  11
month:  07
year:  13
17-Nov-16
Day:  17
month:  11
year:  16
21-Sep-17
Day:  21
month:  09
year:  17
5-Feb-15
Day:  05
month:  02
year:  15
17-Jul-13
Day:  17
month:  07
year:  13
19-Jun-13
Day:  19
month:  06
year:  13
1-Dec-15
Day:  01
month:  12
year:  15
5-Mar-20
Day:  05
month:  03
year:  20
29-Sep-14
Day:  29
month:  09
year:  14
17-May-21
Day:  17
month:  05
year:  21
5-Oct-18
Day:  05
month:  10
year:  18
24-Apr-18
Day:  24
month:  04
year:  18
15-Nov-17
Day:  15
month:  11
year:  17
19-Jun-13
Day:  19
month:  06
year:  13
5-Nov-20
Day:  05
month:  11
year:  20
21-Nov-19
Day:  21
month:  11
year:  19
11-Jul-12
Day:  11
month:  07
year:  12
18-Aug-20
Day:  18
month:  08
year:  20
5-Oct-18
Day:  05
month:  10
year:  18
18-Oct-18
Day:  18
month:  10
year:  18
18-Nov-21
Day:  18
month:  11
year:  21
16-May-17
Day:  16
month:  05
year:  17
26-Feb-19
Day:  26
month:  02
year:  19
4-Jun-19
Day:  04
month:  06
year:  19
28-Mar-19
Day:  28
month:  03
year:  19
24-May-18
Day:  24
month:  05
year:  18
8-Nov-12
Day:  08
month:  11
year:  12
19-Sep-19
Day:  19
month:  09
year:  19
11-Apr-18
Day:  11
month:  04
year:  18
12-Nov-19
Day:  12
month:  11
year:  19
22-Jun-18
Day:  22
month:  06
year:  18
5-Feb-14
Day:  05
month:  02
year:  14
19-Sep-13
Day:  19
month:  09
year:  13
16-May-18
Day:  16
month:  05
year:  18
6-Feb-15
Day:  06
month:  02
year:  15
3-Mar-17
Day:  03
month:  03
year:  17
13-May-16
Day:  13
month:  05
year:  16
19-Jun-19
Day:  19
month:  06
year:  19
11-Nov-15
Day:  11
month:  11
year:  15
6-Dec-17
Day:  06
month:  12
year:  17
7-Feb-13
Day:  07
month:  02
year:  13
17-Oct-17
Day:  17
month:  10
year:  17
11-Jul-18
Day:  11
month:  07
year:  18
14-May-19
Day:  14
month:  05
year:  19
3-Mar-17
Day:  03
month:  03
year:  17
22-Sep-14
Day:  22
month:  09
year:  14
22-Mar-17
Day:  22
month:  03
year:  17
11-Jul-13
Day:  11
month:  07
year:  13
28-Oct-15
Day:  28
month:  10
year:  15
23-Sep-14
Day:  23
month:  09
year:  14
16-May-18
Day:  16
month:  05
year:  18
21-Jun-16
Day:  21
month:  06
year:  16
12-Jul-12
Day:  12
month:  07
year:  12
25-Sep-14
Day:  25
month:  09
year:  14
26-Nov-15
Day:  26
month:  11
year:  15
21-Nov-19
Day:  21
month:  11
year:  19
7-Mar-17
Day:  07
month:  03
year:  17
28-Sep-21
Day:  28
month:  09
year:  21
23-May-13
Day:  23
month:  05
year:  13
27-Nov-12
Day:  27
month:  11
year:  12
15-Nov-21
Day:  15
month:  11
year:  21
12-May-15
Day:  12
month:  05
year:  15
12-Oct-12
Day:  12
month:  10
year:  12
21-Apr-16
Day:  21
month:  04
year:  16
2-Nov-16
Day:  02
month:  11
year:  16
1-Jun-21
Day:  01
month:  06
year:  21
30-Jun-15
Day:  30
month:  06
year:  15
11-Feb-14
Day:  11
month:  02
year:  14
26-Nov-19
Day:  26
month:  11
year:  19
10-Nov-17
Day:  10
month:  11
year:  17
22-Jun-12
Day:  22
month:  06
year:  12
12-Mar-14
Day:  12
month:  03
year:  14
4-Nov-15
Day:  04
month:  11
year:  15
20-Nov-18
Day:  20
month:  11
year:  18
7-Oct-20
Day:  07
month:  10
year:  20
22-Sep-14
Day:  22
month:  09
year:  14
4-Mar-16
Day:  04
month:  03
year:  16
17-Jul-13
Day:  17
month:  07
year:  13
16-Oct-13
Day:  16
month:  10
year:  13
27-Jun-12
Day:  27
month:  06
year:  12
7-Feb-13
Day:  07
month:  02
year:  13
23-Oct-20
Day:  23
month:  10
year:  20
20-Jun-12
Day:  20
month:  06
year:  12
12-Feb-16
Day:  12
month:  02
year:  16
27-Oct-20
Day:  27
month:  10
year:  20
24-Jul-14
Day:  24
month:  07
year:  14
27-May-20
Day:  27
month:  05
year:  20
13-May-16
Day:  13
month:  05
year:  16
31-Mar-16
Day:  31
month:  03
year:  16
9-Nov-21
Day:  09
month:  11
year:  21
11-Feb-15
Day:  11
month:  02
year:  15
7-Jun-16
Day:  07
month:  06
year:  16
24-Apr-18
Day:  24
month:  04
year:  18
17-Jul-18
Day:  17
month:  07
year:  18
4-Mar-16
Day:  04
month:  03
year:  16
1-Apr-21
Day:  01
month:  04
year:  21
14-Nov-13
Day:  14
month:  11
year:  13
3-Jul-19
Day:  03
month:  07
year:  19
7-Oct-20
Day:  07
month:  10
year:  20
19-Nov-20
Day:  19
month:  11
year:  20
2-Mar-21
Day:  02
month:  03
year:  21
29-Mar-19
Day:  29
month:  03
year:  19
7-Dec-17
Day:  07
month:  12
year:  17
16-Nov-16
Day:  16
month:  11
year:  16
17-Jul-20
Day:  17
month:  07
year:  20
20-Apr-18
Day:  20
month:  04
year:  18
7-Feb-20
Day:  07
month:  02
year:  20
16-May-18
Day:  16
month:  05
year:  18
11-Jul-13
Day:  11
month:  07
year:  13
7-Feb-13
Day:  07
month:  02
year:  13
2-Nov-16
Day:  02
month:  11
year:  16
29-Sep-20
Day:  29
month:  09
year:  20
26-Nov-20
Day:  26
month:  11
year:  20
2-Jul-20
Day:  02
month:  07
year:  20
29-Oct-19
Day:  29
month:  10
year:  19
21-Nov-13
Day:  21
month:  11
year:  13
7-Feb-13
Day:  07
month:  02
year:  13
17-Jul-19
Day:  17
month:  07
year:  19
18-Dec-19
Day:  18
month:  12
year:  19
8-Mar-17
Day:  08
month:  03
year:  17
2-Apr-19
Day:  02
month:  04
year:  19
28-Jan-21
Day:  28
month:  01
year:  21
23-Jun-16
Day:  23
month:  06
year:  16
7-Dec-20
Day:  07
month:  12
year:  20
18-Nov-21
Day:  18
month:  11
year:  21
22-Nov-16
Day:  22
month:  11
year:  16
12-Nov-19
Day:  12
month:  11
year:  19
14-Nov-14
Day:  14
month:  11
year:  14
26-Mar-15
Day:  26
month:  03
year:  15
20-Jun-19
Day:  20
month:  06
year:  19
21-Mar-18
Day:  21
month:  03
year:  18
5-Oct-18
Day:  05
month:  10
year:  18
20-Oct-21
Day:  20
month:  10
year:  21
20-Oct-21
Day:  20
month:  10
year:  21
15-Dec-20
Day:  15
month:  12
year:  20
18-Jun-13
Day:  18
month:  06
year:  13
12-Apr-19
Day:  12
month:  04
year:  19
5-Nov-14
Day:  05
month:  11
year:  14
5-Dec-12
Day:  05
month:  12
year:  12
23-Jun-21
Day:  23
month:  06
year:  21
11-Jul-13
Day:  11
month:  07
year:  13
27-Nov-13
Day:  27
month:  11
year:  13
16-May-17
Day:  16
month:  05
year:  17
8-Nov-12
Day:  08
month:  11
year:  12
24-Nov-17
Day:  24
month:  11
year:  17
null: 12 Mar 2021
Day:  12
month:  03
year:  2021
17-Jul-19
Day:  17
month:  07

year:  19
24-Jun-15
Day:  24
month:  06
year:  15
11-Mar-22
Day:  11
month:  03
year:  22
5-Feb-20
Day:  05
month:  02
year:  20
21-Oct-16
Day:  21
month:  10
year:  16
20-Jun-19
Day:  20
month:  06
year:  19
26-Sep-13
Day:  26
month:  09
year:  13
19-Nov-15
Day:  19
month:  11
year:  15
5-Nov-20
Day:  05
month:  11
year:  20
17-May-18
Day:  17
month:  05
year:  18
12-Nov-19
Day:  12
month:  11
year:  19
15-Dec-20
Day:  15
month:  12
year:  20
1-Apr-21
Day:  01
month:  04
year:  21
10-Nov-17
Day:  10
month:  11
year:  17
19-Jun-19
Day:  19
month:  06
year:  19
27-Sep-19
Day:  27
month:  09
year:  19
1-Dec-15
Day:  01
month:  12
year:  15
20-Jul-21
Day:  20
month:  07
year:  21
28-Jul-20
Day:  28
month:  07
year:  20
14-May-21
Day:  14
month:  05
year:  21
10-Apr-18
Day:  10
month:  04
year:  18
6-Nov-13
Day:  06
month:  11
year:  13
24-Mar-22
Day:  24
month:  03
year:  22
27-Oct-16
Day:  27
month:  10
year:  16
3-Sep-12
Day:  03
month:  09
year:  12
8-Jun-18
Day:  08
month:  06
year:  18
19-Jun-19
Day:  19
month:  06
year:  19
7-Oct-16
Day:  07
month:  10
year:  16
6-Oct-17
Day:  06
month:  10
year:  17
20-Jun-18
Day:  20
month:  06
year:  18
18-Feb-22
Day:  18
month:  02
year:  22
6-Feb-20
Day:  06
month:  02
year:  20
6-Oct-17
Day:  06
month:  10
year:  17
22-May-14
Day:  22
month:  05
year:  14
3-Dec-15
Day:  03
month:  12
year:  15
27-Jun-14
Day:  27
month:  06
year:  14
12-Jun-20
Day:  12
month:  06
year:  20
25-May-21
Day:  25
month:  05
year:  21
14-Apr-16
Day:  14
month:  04
year:  16
30-May-18
Day:  30
month:  05
year:  18
21-Jun-12
Day:  21
month:  06
year:  12
11-Jul-18
Day:  11
month:  07
year:  18
1-Mar-17
Day:  01
month:  03
year:  17
12-Jul-12
Day:  12
month:  07
year:  12
5-Feb-14
Day:  05
month:  02
year:  14
9-Oct-13
Day:  09
month:  10
year:  13
7-Mar-19
Day:  07
month:  03
year:  19
7-Feb-14
Day:  07
month:  02
year:  14
11-Dec-14
Day:  11
month:  12
year:  14
11-Jul-13
Day:  11
month:  07
year:  13
15-Nov-17
Day:  15
month:  11
year:  17
23-Jun-16
Day:  23
month:  06
year:  16
3-Dec-20
Day:  03
month:  12
year:  20
6-Mar-15
Day:  06
month:  03
year:  15
5-Jun-13
Day:  05
month:  06
year:  13
10-Jun-16
Day:  10
month:  06
year:  16
23-Jun-16
Day:  23
month:  06
year:  16
14-Nov-19
Day:  14
month:  11
year:  19
14-Oct-20
Day:  14
month:  10
year:  20
22-May-18
Day:  22
month:  05
year:  18
5-Nov-13
Day:  05
month:  11
year:  13
23-Mar-22
Day:  23
month:  03
year:  22
21-Nov-17
Day:  21
month:  11
year:  17
10-Dec-13
Day:  10
month:  12
year:  13
20-Mar-13
Day:  20
month:  03
year:  13
28-Feb-19
Day:  28
month:  02
year:  19
24-Mar-22
Day:  24
month:  03
year:  22
30-Jun-15
Day:  30
month:  06
year:  15
27-May-21
Day:  27
month:  05
year:  21
6-Oct-17
Day:  06
month:  10
year:  17
5-Dec-12
Day:  05
month:  12
year:  12
20-Oct-21
Day:  20
month:  10
year:  21
20-Oct-17
Day:  20
month:  10
year:  17
25-Jun-14
Day:  25
month:  06
year:  14
18-Dec-19
Day:  18
month:  12
year:  19
29-May-13
Day:  29
month:  05
year:  13
12-Feb-16
Day:  12
month:  02
year:  16
12-Nov-18
Day:  12
month:  11
year:  18
5-Oct-19
Day:  05
month:  10
year:  19
24-Apr-18
Day:  24
month:  04
year:  18
21-Jul-21
Day:  21
month:  07
year:  21
21-Nov-15
Day:  21
month:  11
year:  15
19-Jun-19
Day:  19
month:  06
year:  19
26-Jun-14
Day:  26
month:  06
year:  14
26-Mar-14
Day:  26
month:  03
year:  14
29-Sep-14
Day:  29
month:  09
year:  14
5-Nov-19
Day:  05
month:  11
year:  19
28-Oct-20
Day:  28
month:  10
year:  20
19-Jun-13
Day:  19
month:  06
year:  13
4-Dec-20
Day:  04
month:  12
year:  20
14-Nov-13
Day:  14
month:  11
year:  13
5-Oct-18
Day:  05
month:  10
year:  18
2-Mar-18
Day:  02
month:  03
year:  18
27-Jun-17
Day:  27
month:  06
year:  17
15-Nov-16
Day:  15
month:  11
year:  16
22-May-18
Day:  22
month:  05
year:  18
2-Jul-14
Day:  02
month:  07
year:  14
7-Jul-16
Day:  07
month:  07
year:  16
26-Jun-12
Day:  26
month:  06
year:  12
12-May-15
Day:  12
month:  05
year:  15
16-Oct-13
Day:  16
month:  10
year:  13
12-Mar-14
Day:  12
month:  03
year:  14
23-Oct-15
Day:  23
month:  10
year:  15
28-Feb-18
Day:  28
month:  02
year:  18
29-Jun-17
Day:  29
month:  06
year:  17
13-May-19
Day:  13
month:  05
year:  19
15-Jul-20
Day:  15
month:  07
year:  20
31-Mar-22
Day:  31
month:  03
year:  22
17-Mar-16
Day:  17
month:  03
year:  16
24-Mar-17
Day:  24
month:  03
year:  17
11-Dec-20
Day:  11
month:  12
year:  20
23-Jan-20
Day:  23
month:  01
year:  20
21-Oct-16
Day:  21
month:  10
year:  16
5-Feb-15
Day:  05
month:  02
year:  15
24-Mar-17
Day:  24
month:  03
year:  17
30-Mar-22
Day:  30
month:  03
year:  22
6-Nov-13
Day:  06
month:  11
year:  13
25-Oct-18
Day:  25
month:  10
year:  18
23-Oct-15
Day:  23
month:  10
year:  15
13-Nov-21
Day:  13
month:  11
year:  21
25-May-17
Day:  25
month:  05
year:  17
20-Sep-12
Day:  20
month:  09
year:  12
16-Oct-14
Day:  16
month:  10
year:  14
23-Jun-21
Day:  23
month:  06
year:  21
13-Mar-13
Day:  13
month:  03
year:  13
23-Oct-20
Day:  23
month:  10
year:  20
22-Jun-18
Day:  22
month:  06
year:  18
12-Oct-12
Day:  12
month:  10
year:  12
18-Mar-20
Day:  18
month:  03
year:  20
22-Oct-20
Day:  22
month:  10
year:  20
24-Mar-17
Day:  24
month:  03
year:  17
5-Jun-12
Day:  05
month:  06
year:  12
20-May-21
Day:  20
month:  05
year:  21
20-Apr-18
Day:  20
month:  04
year:  18
8-Nov-12
Day:  08
month:  11
year:  12
11-Jul-18
Day:  11
month:  07
year:  18
18-May-21
Day:  18
month:  05
year:  21
13-Nov-18
Day:  13
month:  11
year:  18
22-Oct-20
Day:  22
month:  10
year:  20
25-May-17
Day:  25
month:  05
year:  17
10-Nov-16
Day:  10
month:  11
year:  16
14-Dec-16
Day:  14
month:  12
year:  16
29-May-13
Day:  29
month:  05
year:  13
1-Mar-19
Day:  01
month:  03
year:  19
28-Feb-19
Day:  28
month:  02
year:  19
25-May-17
Day:  25
month:  05
year:  17
18-Jun-20
Day:  18
month:  06
year:  20
21-Nov-17
Day:  21
month:  11
year:  17
5-Feb-20
Day:  05
month:  02
year:  20
28-Sep-21
Day:  28
month:  09
year:  21
5-Feb-14
Day:  05
month:  02
year:  14
25-May-21
Day:  25
month:  05
year:  21
3-Dec-21
Day:  03
month:  12
year:  21
22-May-18
Day:  22
month:  05
year:  18
21-Jun-19
Day:  21
month:  06
year:  19
22-Mar-16
Day:  22
month:  03
year:  16
7-Feb-13
Day:  07
month:  02
year:  13
19-Sep-19
Day:  19
month:  09
year:  19
26-Jun-12
Day:  26
month:  06
year:  12
22-Sep-14
Day:  22
month:  09
year:  14
1-Dec-12
Day:  01
month:  12
year:  12
23-Mar-18
Day:  23
month:  03
year:  18
5-Feb-14
Day:  05
month:  02
year:  14
28-Feb-18
Day:  28
month:  02
year:  18
12-Dec-18
Day:  12
month:  12
year:  18
5-Feb-20
Day:  05
month:  02
year:  20
1-Apr-21
Day:  01
month:  04
year:  21
6-May-21
Day:  06
month:  05
year:  21
16-May-19
Day:  16
month:  05
year:  19
22-Nov-16
Day:  22
month:  11
year:  16
10-Mar-22
Day:  10
month:  03
year:  22
4-Mar-20
Day:  04
month:  03
year:  20
19-Jul-17
Day:  19
month:  07
year:  17
15-Dec-17
Day:  15
month:  12
year:  17
13-Dec-12
Day:  13
month:  12
year:  12
1-Jul-14
Day:  01
month:  07
year:  14
13-May-19
Day:  13
month:  05
year:  19
21-Jun-16
Day:  21
month:  06
year:  16
14-Nov-12
Day:  14
month:  11
year:  12
8-Jul-15
Day:  08
month:  07
year:  15
20-Nov-12
Day:  20
month:  11
year:  12
23-May-13
Day:  23
month:  05
year:  13
17-Mar-16
Day:  17
month:  03
year:  16
27-Nov-12
Day:  27
month:  11
year:  12
16-Nov-17
Day:  16
month:  11
year:  17
13-Dec-12
Day:  13
month:  12
year:  12
14-Apr-21
Day:  14
month:  04
year:  21
27-Feb-18
Day:  27
month:  02
year:  18
20-Nov-18
Day:  20
month:  11
year:  18
15-Oct-19
Day:  15
month:  10
year:  19

In [43]:
ArtInfo.head(20)

,Artist,Birth,Death,Age,Alive?,Art Title,DoC,Currency,price,low_estimate,...,Sold,Est Accuracy,Dimentions,close date,Auction Title,relPop,relPopEarly,relPopChange,closeMonth,closeYear
0,moise kisling,1891,1953,62,0,Nu,1931,USD,81250.00,40000.0,...,1,1,(73 x 54 cm.),17,IMPRESSIONIST & MODERN ART DAY SALE,None,None,None,11,16
1,george edward lodge,1860,1954,94,0,Golden eagle on a branch,0,USD,2656.25,1500.0,...,1,1,(34.6 x 24.7 cm.),18,"The Astor Collection from Tillypronie, Aberdee...",None,None,None,12,17
2,helen frankenthaler,1928,2011,83,0,Cinnamon Burn,1968,USD,663750.00,300000.0,...,1,1,(304.8 x 208.2 cm.),16,POST-WAR & CONTEMPORARY MORNING SESSION,None,None,None,05,13
3,sir john alfred arnesby brown,1866,1955,89,0,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,...,1,1,(66 x 91.4 cm.),13,VICTORIAN & BRITISH IMPRESSIONIST ART,None,None,None,12,12
4,raymond pettibon,1957,0,65,1,Untitled (But come up),1987,USD,9375.00,3750.0,...,1,1,(35.3 x 27.7cm.),20,First Open Online,None,None,None,09,18
5,keltie ferris,1977,0,45,1,Ghost Trees,2018,USD,50000.00,30000.0,...,1,1,(182.9 x 152.4 cm.),27,POST-WAR TO PRESENT,None,None,None,09,18
7,robert rauschenberg,1925,2008,83,0,Calendar,1962,USD,2741000.00,3000000.0,...,1,-1,(243.8 x 152.4 cm.),13,POST-WAR AND CONTEMPORARY ART EVENING SALE,None,None,None,05,15
8,rembrandt harmensz. van rijn,1606,1669,63,0,Christ and the Woman of Samaria: an Arched pri...,70,USD,1718.75,1250.0,...,1,0,0,04,500 YEARS OF PRINTMAKING,None,None,None,12,13
10,"george howard, 9th earl of carlisle",1843,1911,68,0,Study of a standing draped female figure,0,USD,2343.75,1250.0,...,1,1,(31.1 x 15 cm.),13,VICTORIAN PRE-RAPHAELITE & BRITISH IMPRESSIONI...,None,None,None,12,17
11,karel appel,1921,2006,85,0,Tétes dans Tempête (Heads in the Tempest),1960,USD,144375.00,126000.0,...,1,0,0,24,POST-WAR AND CONTEMPORARY ART,None,None,None,04,18
13,alberto giacometti,1901,1966,65,0,Femme assise et verre à pied,0,USD,41895.00,21000.0,...,1,1,0,31,OEUVRES MODERNES SUR PAPIER,None,None,None,03,16
14,lucebert,1924,1994,70,0,Untitled,0,USD,7276.50,4200.0,...,1,1,0,26,20th/21st Century: Amsterdam,None,None,None,04,22
17,odilon redon,1840,1916,76,0,Visage-Germination,1888,USD,233000.00,100000.0,...,1,1,(52.5 x 37.2 cm.),05,A DIALOGUE THROUGH ART: WORKS FROM THE JAN KRU...,None,None,None,11,13
18,jack whitten,1939,2018,79,0,Virgin Space Loop #19,2012,USD,87500.00,60000.0,...,1,1,(30.5 x 30.5 cm.),16,POST-WAR AND CONTEMPORARY ART AFTERNOON SESSION,None,None,None,05,19
20,nicolas party,1980,0,42,1,Still Life No 103,2012,USD,10625.00,2500.0,...,1,1,(16.5 x 22.2cm.),28,POST-WAR TO PRESENT,None,None,None,06,18
21,samuel holburn fyfe,1822,1905,83,0,The clipper John R. Worcester outward-bound fr...,0,USD,3906.25,3125.0,...,1,0,(71 x 111.8 cm.),05,MARITIME ART,None,None,None,06,14
23,pedro friedeberg,1936,0,86,1,Pair of Hand Chairs,0,USD,18750.00,15000.0,...,1,0,(86.4 x 48.3 x 50.8 cm.),30,Latin American Art Online,None,None,None,05,18
24,gunther gerzso,1915,2000,85,0,Trópico calizo,1992,USD,137500.00,70000.0,...,1,1,(81.3 x 100.3 cm.),30,LATIN AMERICAN ART,None,None,None,07,20
25,brassaï,1899,1950,51,0,"Graffiti (Serie IV, Masques et Visages), 1935-...",0,USD,18750.00,10000.0,...,1,1,(40 x 30.4 cm.),14,The Unseen Eye: Photographs from the W.M. Hunt...,None,None,None,10,20
26,andy warhol,1928,1987,59,0,Marilyn Monroe (Marilyn): one print,0,USD,187500.00,100000.0,...,1,1,(914 x 914 mm.),22,PRINTS & MULTIPLES,None,None,None,10,21

In [44]:
ArtInfo.shape

(1187, 21)

In [45]:
ArtInfo.to_csv("Christies_Art_Objects_Clean.csv", index = False)

## Gathers Artist Popularity

In [46]:
from bs4 import BeautifulSoup
import requests, lxml
import bs4
import re
import pandas as pd

headers = {
    'User-agent':
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582"
}

def getPopularity(search_term):
    "Gives you the number of hits on yahoo"
    html = requests.get('https://search.yahoo.com/search?p={0}'.format(search_term),headers=headers, ).text
    soup = BeautifulSoup(html, 'lxml')
    results = soup.body.find_all(string=re.compile('.*{0}.*'.format('search results')), recursive=True)
    return results[0][6:-15]

In [47]:
ArtInfo = pd.read_csv ('Christies_Art_Objects_Clean.csv')

In [48]:
#add a column for relative popularity

absPop = [None] * ArtInfo.shape[0] #as long as num rows

ArtInfo['absPop'] = absPop

In [49]:
counter = 0
for items in ArtInfo["Artist"]:
    
    print("Counter:", counter)
    
    try:
        ArtInfo.at[counter, 'absPop'] = getPopularity(items)
    except:
        ArtInfo.at[counter, 'absPop'] = 0
    
    if ((counter % 50) == 0):
        ArtInfo.to_csv("absPop.csv", index = False)
    
    counter += 1

ArtInfo.to_csv("absPop.csv", index = False)

Counter: 0
Counter: 1
Counter: 2
Counter: 3
Counter: 4
Counter: 5
Counter: 6
Counter: 7
Counter: 8
Counter: 9
Counter: 10
Counter: 11
Counter: 12
Counter: 13
Counter: 14
Counter: 15
Counter: 16
Counter: 17
Counter: 18
Counter: 19
Counter: 20
Counter: 21
Counter: 22
Counter: 23
Counter: 24
Counter: 25
Counter: 26
Counter: 27
Counter: 28
Counter: 29
Counter: 30
Counter: 31
Counter: 32
Counter: 33
Counter: 34
Counter: 35
Counter: 36
Counter: 37
Counter: 38
Counter: 39
Counter: 40
Counter: 41
Counter: 42
Counter: 43
Counter: 44
Counter: 45
Counter: 46
Counter: 47
Counter: 48
Counter: 49
Counter: 50
Counter: 51
Counter: 52
Counter: 53
Counter: 54
Counter: 55
Counter: 56
Counter: 57
Counter: 58
Counter: 59
Counter: 60
Counter: 61
Counter: 62
Counter: 63
Counter: 64
Counter: 65
Counter: 66
Counter: 67
Counter: 68
Counter: 69
Counter: 70
Counter: 71
Counter: 72
Counter: 73
Counter: 74
Counter: 75
Counter: 76
Counter: 77
Counter: 78
Counter: 79
Counter: 80
Counter: 81
Counter: 82
Counter: 83
Counter: 84
Counter: 85
Counter: 86
Counter: 87
Counter: 88
Counter: 89
Counter: 90
Counter: 91
Counter: 92
Counter: 93
Counter: 94
Counter: 95
Counter: 96
Counter: 97
Counter: 98
Counter: 99
Counter: 100
Counter: 101
Counter: 102
Counter: 103
Counter: 104
Counter: 105
Counter: 106
Counter: 107
Counter: 108
Counter: 109
Counter: 110
Counter: 111
Counter: 112
Counter: 113
Counter: 114
Counter: 115
Counter: 116
Counter: 117
Counter: 118
Counter: 119
Counter: 120
Counter: 121
Counter: 122
Counter: 123
Counter: 124
Counter: 125
Counter: 126
Counter: 127
Counter: 128
Counter: 129
Counter: 130
Counter: 131
Counter: 132
Counter: 133
Counter: 134
Counter: 135
Counter: 136
Counter: 137
Counter: 138
Counter: 139
Counter: 140
Counter: 141
Counter: 142
Counter: 143
Counter: 144
Counter: 145
Counter: 146
Counter: 147
Counter: 148
Counter: 149
Counter: 150
Counter: 151
Counter: 152
Counter: 153
Counter: 154
Counter: 155
Counter: 156
Counter: 157
Counter: 158
Counter: 159
Counter: 160
Counter: 161
Counter: 162
Counter: 163
Counter: 164
Counter: 165
Counter: 166
Counter: 167
Counter: 168
Counter: 169
Counter: 170
Counter: 171
Counter: 172
Counter: 173
Counter: 174
Counter: 175
Counter: 176
Counter: 177
Counter: 178
Counter: 179
Counter: 180
Counter: 181
Counter: 182
Counter: 183
Counter: 184
Counter: 185
Counter: 186
Counter: 187
Counter: 188
Counter: 189
Counter: 190
Counter: 191
Counter: 192
Counter: 193
Counter: 194
Counter: 195
Counter: 196
Counter: 197
Counter: 198
Counter: 199
Counter: 200
Counter: 201
Counter: 202
Counter: 203
Counter: 204
Counter: 205
Counter: 206
Counter: 207
Counter: 208
Counter: 209
Counter: 210
Counter: 211
Counter: 212
Counter: 213
Counter: 214
Counter: 215
Counter: 216
Counter: 217
Counter: 218
Counter: 219
Counter: 220
Counter: 221
Counter: 222
Counter: 223
Counter: 224
Counter: 225
Counter: 226
Counter: 227
Counter: 228
Counter: 229
Counter: 230
Counter: 231
Counter: 232
Counter: 233
Counter: 234
Counter: 235
Counter: 236
Counter: 237
Counter: 238
Counter: 239
Counter: 240
Counter: 241
Counter: 242
Counter: 243
Counter: 244
Counter: 245
Counter: 246
Counter: 247
Counter: 248
Counter: 249
Counter: 250
Counter: 251
Counter: 252
Counter: 253
Counter: 254
Counter: 255
Counter: 256
Counter: 257
Counter: 258
Counter: 259
Counter: 260
Counter: 261
Counter: 262
Counter: 263
Counter: 264
Counter: 265
Counter: 266
Counter: 267
Counter: 268
Counter: 269
Counter: 270
Counter: 271
Counter: 272
Counter: 273
Counter: 274
Counter: 275
Counter: 276
Counter: 277
Counter: 278
Counter: 279
Counter: 280
Counter: 281
Counter: 282
Counter: 283
Counter: 284
Counter: 285
Counter: 286
Counter: 287
Counter: 288
Counter: 289
Counter: 290
Counter: 291
Counter: 292
Counter: 293
Counter: 294
Counter: 295
Counter: 296
Counter: 297
Counter: 298
Counter: 299
Counter: 300
Counter: 301
Counter: 302
Counter: 303
Counter: 304
Counter: 305
Counter: 306
Counter: 307
Counter: 308
Counter: 309
Counter: 310
Counter: 311
Counter: 312
Counter: 313
Counter: 314
Counter: 315
Counter: 316
Counter: 317
Counter: 318
Counter: 319
Counter: 320
Counter: 321
Counter: 322
Counter: 323
Counter: 324
Counter: 325
Counter: 326
Counter: 327
Counter: 328
Counter: 329
Counter: 330
Counter: 331
Counter: 332
Counter: 333
Counter: 334
Counter: 335
Counter: 336
Counter: 337
Counter: 338
Counter: 339
Counter: 340
Counter: 341
Counter: 342
Counter: 343
Counter: 344
Counter: 345
Counter: 346
Counter: 347
Counter: 348
Counter: 349
Counter: 350
Counter: 351
Counter: 352
Counter: 353
Counter: 354
Counter: 355
Counter: 356
Counter: 357
Counter: 358
Counter: 359
Counter: 360
Counter: 361
Counter: 362
Counter: 363
Counter: 364
Counter: 365
Counter: 366
Counter: 367
Counter: 368
Counter: 369
Counter: 370
Counter: 371
Counter: 372
Counter: 373
Counter: 374
Counter: 375
Counter: 376
Counter: 377
Counter: 378
Counter: 379
Counter: 380
Counter: 381
Counter: 382
Counter: 383
Counter: 384
Counter: 385
Counter: 386
Counter: 387
Counter: 388
Counter: 389
Counter: 390
Counter: 391
Counter: 392
Counter: 393
Counter: 394
Counter: 395
Counter: 396
Counter: 397
Counter: 398
Counter: 399
Counter: 400
Counter: 401
Counter: 402
Counter: 403
Counter: 404
Counter: 405
Counter: 406
Counter: 407
Counter: 408
Counter: 409
Counter: 410
Counter: 411
Counter: 412
Counter: 413
Counter: 414
Counter: 415
Counter: 416
Counter: 417
Counter: 418
Counter: 419
Counter: 420
Counter: 421
Counter: 422
Counter: 423
Counter: 424
Counter: 425
Counter: 426
Counter: 427
Counter: 428
Counter: 429
Counter: 430
Counter: 431
Counter: 432
Counter: 433
Counter: 434
Counter: 435
Counter: 436
Counter: 437
Counter: 438
Counter: 439
Counter: 440
Counter: 441
Counter: 442
Counter: 443
Counter: 444
Counter: 445
Counter: 446
Counter: 447
Counter: 448
Counter: 449
Counter: 450
Counter: 451
Counter: 452
Counter: 453
Counter: 454
Counter: 455
Counter: 456
Counter: 457
Counter: 458
Counter: 459
Counter: 460
Counter: 461
Counter: 462
Counter: 463
Counter: 464
Counter: 465
Counter: 466
Counter: 467
Counter: 468
Counter: 469
Counter: 470
Counter: 471
Counter: 472
Counter: 473
Counter: 474
Counter: 475
Counter: 476
Counter: 477
Counter: 478
Counter: 479
Counter: 480
Counter: 481
Counter: 482
Counter: 483
Counter: 484
Counter: 485
Counter: 486
Counter: 487
Counter: 488
Counter: 489
Counter: 490
Counter: 491
Counter: 492
Counter: 493
Counter: 494
Counter: 495
Counter: 496
Counter: 497
Counter: 498
Counter: 499
Counter: 500
Counter: 501
Counter: 502
Counter: 503
Counter: 504
Counter: 505
Counter: 506
Counter: 507
Counter: 508
Counter: 509
Counter: 510
Counter: 511
Counter: 512
Counter: 513
Counter: 514
Counter: 515
Counter: 516
Counter: 517
Counter: 518
Counter: 519
Counter: 520
Counter: 521
Counter: 522
Counter: 523
Counter: 524
Counter: 525
Counter: 526
Counter: 527
Counter: 528
Counter: 529
Counter: 530
Counter: 531
Counter: 532
Counter: 533
Counter: 534
Counter: 535
Counter: 536
Counter: 537
Counter: 538
Counter: 539
Counter: 540
Counter: 541
Counter: 542
Counter: 543
Counter: 544
Counter: 545
Counter: 546
Counter: 547
Counter: 548
Counter: 549
Counter: 550
Counter: 551
Counter: 552
Counter: 553
Counter: 554
Counter: 555
Counter: 556
Counter: 557
Counter: 558
Counter: 559
Counter: 560
Counter: 561
Counter: 562
Counter: 563
Counter: 564
Counter: 565
Counter: 566
Counter: 567
Counter: 568
Counter: 569
Counter: 570
Counter: 571
Counter: 572
Counter: 573
Counter: 574
Counter: 575
Counter: 576
Counter: 577
Counter: 578
Counter: 579
Counter: 580
Counter: 581
Counter: 582
Counter: 583
Counter: 584
Counter: 585
Counter: 586
Counter: 587
Counter: 588
Counter: 589
Counter: 590
Counter: 591
Counter: 592
Counter: 593
Counter: 594
Counter: 595
Counter: 596
Counter: 597
Counter: 598
Counter: 599
Counter: 600
Counter: 601
Counter: 602
Counter: 603
Counter: 604
Counter: 605
Counter: 606
Counter: 607
Counter: 608
Counter: 609
Counter: 610
Counter: 611
Counter: 612
Counter: 613
Counter: 614
Counter: 615
Counter: 616
Counter: 617
Counter: 618
Counter: 619
Counter: 620
Counter: 621
Counter: 622
Counter: 623
Counter: 624
Counter: 625
Counter: 626
Counter: 627
Counter: 628
Counter: 629
Counter: 630
Counter: 631
Counter: 632
Counter: 633
Counter: 634
Counter: 635
Counter: 636
Counter: 637
Counter: 638

Counter: 639
Counter: 640
Counter: 641
Counter: 642
Counter: 643
Counter: 644
Counter: 645
Counter: 646
Counter: 647
Counter: 648
Counter: 649
Counter: 650
Counter: 651
Counter: 652
Counter: 653
Counter: 654
Counter: 655
Counter: 656
Counter: 657
Counter: 658
Counter: 659
Counter: 660
Counter: 661
Counter: 662
Counter: 663
Counter: 664
Counter: 665
Counter: 666
Counter: 667
Counter: 668
Counter: 669
Counter: 670
Counter: 671
Counter: 672
Counter: 673
Counter: 674
Counter: 675
Counter: 676
Counter: 677
Counter: 678
Counter: 679
Counter: 680
Counter: 681
Counter: 682
Counter: 683
Counter: 684
Counter: 685
Counter: 686
Counter: 687
Counter: 688
Counter: 689
Counter: 690
Counter: 691
Counter: 692
Counter: 693
Counter: 694
Counter: 695
Counter: 696
Counter: 697
Counter: 698
Counter: 699
Counter: 700
Counter: 701
Counter: 702
Counter: 703
Counter: 704
Counter: 705
Counter: 706
Counter: 707
Counter: 708
Counter: 709
Counter: 710
Counter: 711
Counter: 712
Counter: 713
Counter: 714
Counter: 715
Counter: 716
Counter: 717
Counter: 718
Counter: 719
Counter: 720
Counter: 721
Counter: 722
Counter: 723
Counter: 724
Counter: 725
Counter: 726
Counter: 727
Counter: 728
Counter: 729
Counter: 730
Counter: 731
Counter: 732
Counter: 733
Counter: 734
Counter: 735
Counter: 736
Counter: 737
Counter: 738
Counter: 739
Counter: 740
Counter: 741
Counter: 742
Counter: 743
Counter: 744
Counter: 745
Counter: 746
Counter: 747
Counter: 748
Counter: 749
Counter: 750
Counter: 751
Counter: 752
Counter: 753
Counter: 754
Counter: 755
Counter: 756
Counter: 757
Counter: 758
Counter: 759
Counter: 760
Counter: 761
Counter: 762
Counter: 763
Counter: 764
Counter: 765
Counter: 766
Counter: 767
Counter: 768
Counter: 769
Counter: 770
Counter: 771
Counter: 772
Counter: 773
Counter: 774
Counter: 775
Counter: 776
Counter: 777
Counter: 778
Counter: 779
Counter: 780
Counter: 781
Counter: 782
Counter: 783
Counter: 784
Counter: 785
Counter: 786
Counter: 787
Counter: 788
Counter: 789
Counter: 790
Counter: 791
Counter: 792
Counter: 793
Counter: 794
Counter: 795
Counter: 796
Counter: 797
Counter: 798
Counter: 799
Counter: 800
Counter: 801
Counter: 802
Counter: 803
Counter: 804
Counter: 805
Counter: 806
Counter: 807
Counter: 808
Counter: 809
Counter: 810
Counter: 811
Counter: 812
Counter: 813
Counter: 814
Counter: 815
Counter: 816
Counter: 817
Counter: 818
Counter: 819
Counter: 820
Counter: 821
Counter: 822
Counter: 823
Counter: 824
Counter: 825
Counter: 826
Counter: 827
Counter: 828
Counter: 829
Counter: 830
Counter: 831
Counter: 832
Counter: 833
Counter: 834
Counter: 835
Counter: 836
Counter: 837
Counter: 838
Counter: 839
Counter: 840
Counter: 841
Counter: 842
Counter: 843
Counter: 844
Counter: 845
Counter: 846
Counter: 847
Counter: 848
Counter: 849
Counter: 850
Counter: 851
Counter: 852
Counter: 853
Counter: 854
Counter: 855
Counter: 856
Counter: 857
Counter: 858
Counter: 859
Counter: 860
Counter: 861
Counter: 862
Counter: 863
Counter: 864
Counter: 865
Counter: 866
Counter: 867
Counter: 868
Counter: 869
Counter: 870
Counter: 871
Counter: 872
Counter: 873
Counter: 874
Counter: 875
Counter: 876
Counter: 877
Counter: 878
Counter: 879
Counter: 880
Counter: 881
Counter: 882
Counter: 883
Counter: 884
Counter: 885
Counter: 886
Counter: 887
Counter: 888
Counter: 889
Counter: 890
Counter: 891
Counter: 892
Counter: 893
Counter: 894
Counter: 895
Counter: 896
Counter: 897
Counter: 898
Counter: 899
Counter: 900
Counter: 901
Counter: 902
Counter: 903
Counter: 904
Counter: 905
Counter: 906
Counter: 907
Counter: 908
Counter: 909
Counter: 910
Counter: 911
Counter: 912
Counter: 913
Counter: 914
Counter: 915
Counter: 916
Counter: 917
Counter: 918
Counter: 919
Counter: 920
Counter: 921
Counter: 922
Counter: 923
Counter: 924
Counter: 925
Counter: 926
Counter: 927
Counter: 928
Counter: 929
Counter: 930
Counter: 931
Counter: 932
Counter: 933
Counter: 934
Counter: 935
Counter: 936
Counter: 937
Counter: 938
Counter: 939
Counter: 940
Counter: 941
Counter: 942
Counter: 943
Counter: 944
Counter: 945
Counter: 946
Counter: 947
Counter: 948
Counter: 949
Counter: 950
Counter: 951
Counter: 952
Counter: 953
Counter: 954
Counter: 955
Counter: 956
Counter: 957
Counter: 958
Counter: 959
Counter: 960
Counter: 961
Counter: 962
Counter: 963
Counter: 964
Counter: 965
Counter: 966
Counter: 967
Counter: 968
Counter: 969
Counter: 970
Counter: 971
Counter: 972
Counter: 973
Counter: 974
Counter: 975
Counter: 976
Counter: 977
Counter: 978
Counter: 979
Counter: 980
Counter: 981
Counter: 982
Counter: 983
Counter: 984
Counter: 985
Counter: 986
Counter: 987
Counter: 988
Counter: 989
Counter: 990
Counter: 991
Counter: 992
Counter: 993
Counter: 994
Counter: 995
Counter: 996
Counter: 997
Counter: 998
Counter: 999
Counter: 1000
Counter: 1001
Counter: 1002
Counter: 1003
Counter: 1004
Counter: 1005
Counter: 1006
Counter: 1007
Counter: 1008
Counter: 1009
Counter: 1010
Counter: 1011
Counter: 1012
Counter: 1013
Counter: 1014
Counter: 1015
Counter: 1016
Counter: 1017
Counter: 1018
Counter: 1019
Counter: 1020
Counter: 1021
Counter: 1022
Counter: 1023
Counter: 1024
Counter: 1025
Counter: 1026
Counter: 1027
Counter: 1028
Counter: 1029
Counter: 1030
Counter: 1031
Counter: 1032
Counter: 1033
Counter: 1034
Counter: 1035
Counter: 1036
Counter: 1037
Counter: 1038
Counter: 1039
Counter: 1040
Counter: 1041
Counter: 1042
Counter: 1043
Counter: 1044
Counter: 1045
Counter: 1046
Counter: 1047
Counter: 1048
Counter: 1049
Counter: 1050
Counter: 1051
Counter: 1052
Counter: 1053
Counter: 1054
Counter: 1055
Counter: 1056
Counter: 1057
Counter: 1058
Counter: 1059
Counter: 1060
Counter: 1061
Counter: 1062
Counter: 1063
Counter: 1064
Counter: 1065
Counter: 1066
Counter: 1067
Counter: 1068
Counter: 1069
Counter: 1070
Counter: 1071
Counter: 1072
Counter: 1073
Counter: 1074
Counter: 1075
Counter: 1076
Counter: 1077
Counter: 1078
Counter: 1079
Counter: 1080
Counter: 1081
Counter: 1082
Counter: 1083
Counter: 1084
Counter: 1085
Counter: 1086
Counter: 1087
Counter: 1088
Counter: 1089
Counter: 1090
Counter: 1091
Counter: 1092
Counter: 1093
Counter: 1094
Counter: 1095
Counter: 1096
Counter: 1097
Counter: 1098
Counter: 1099
Counter: 1100
Counter: 1101
Counter: 1102
Counter: 1103
Counter: 1104
Counter: 1105
Counter: 1106
Counter: 1107
Counter: 1108
Counter: 1109
Counter: 1110
Counter: 1111
Counter: 1112
Counter: 1113
Counter: 1114
Counter: 1115
Counter: 1116
Counter: 1117
Counter: 1118
Counter: 1119
Counter: 1120
Counter: 1121
Counter: 1122
Counter: 1123
Counter: 1124
Counter: 1125
Counter: 1126
Counter: 1127
Counter: 1128
Counter: 1129
Counter: 1130
Counter: 1131
Counter: 1132
Counter: 1133
Counter: 1134
Counter: 1135
Counter: 1136
Counter: 1137
Counter: 1138
Counter: 1139
Counter: 1140
Counter: 1141
Counter: 1142
Counter: 1143
Counter: 1144
Counter: 1145
Counter: 1146
Counter: 1147
Counter: 1148
Counter: 1149
Counter: 1150
Counter: 1151
Counter: 1152
Counter: 1153
Counter: 1154
Counter: 1155
Counter: 1156
Counter: 1157
Counter: 1158
Counter: 1159
Counter: 1160
Counter: 1161
Counter: 1162
Counter: 1163
Counter: 1164
Counter: 1165
Counter: 1166
Counter: 1167
Counter: 1168
Counter: 1169
Counter: 1170
Counter: 1171
Counter: 1172
Counter: 1173
Counter: 1174
Counter: 1175
Counter: 1176
Counter: 1177
Counter: 1178
Counter: 1179
Counter: 1180
Counter: 1181
Counter: 1182
Counter: 1183
Counter: 1184
Counter: 1185
Counter: 1186

In [49]:
ArtInfo.head(2000)

,Artist,Birth,Death,Age,Alive?,Art Title,DoC,Currency,price,low_estimate,...,Est Accuracy,Dimentions,close date,Auction Title,relPop,relPopEarly,relPopChange,closeMonth,closeYear,absPop
0,moise kisling,1891,1953,62,0,Nu,1931,USD,81250.00,40000.0,...,1,(73 x 54 cm.),17,IMPRESSIONIST & MODERN ART DAY SALE,NaN,NaN,NaN,11,16,0
1,george edward lodge,1860,1954,94,0,Golden eagle on a branch,0,USD,2656.25,1500.0,...,1,(34.6 x 24.7 cm.),18,"The Astor Collection from Tillypronie, Aberdee...",NaN,NaN,NaN,12,17,0
2,helen frankenthaler,1928,2011,83,0,Cinnamon Burn,1968,USD,663750.00,300000.0,...,1,(304.8 x 208.2 cm.),16,POST-WAR & CONTEMPORARY MORNING SESSION,NaN,NaN,NaN,5,13,0
3,sir john alfred arnesby brown,1866,1955,89,0,"The Round Tower, Haddiscoe",0,USD,26562.50,15000.0,...,1,(66 x 91.4 cm.),13,VICTORIAN & BRITISH IMPRESSIONIST ART,NaN,NaN,NaN,12,12,0
4,raymond pettibon,1957,0,65,1,Untitled (But come up),1987,USD,9375.00,3750.0,...,1,(35.3 x 27.7cm.),20,First Open Online,NaN,NaN,NaN,9,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1182,walter richard sickert,1860,1942,82,0,"The Façade of St. Mark's, Venice",0,USD,25000.00,25000.0,...,-1,(15.5 x 24.1 cm.),13,MODERN BRITISH AND IRISH ART DAY SALE,NaN,NaN,NaN,12,12,0
1183,robert delaunay,1885,1941,56,0,Manège de cochons,1922,USD,651000.00,525000.0,...,0,0,14,OEUVRES MODERNES SUR PAPIER / ART IMPRESSIONNI...,NaN,NaN,NaN,4,21,0
1184,henry moore,1898,1986,88,0,Two Piece Reclining Figure: Armless,1975,USD,985937.50,625000.0,...,1,0,27,IMPRESSIONIST AND MODERN ART EVENING SALE,NaN,NaN,NaN,2,18,0
1185,walter gay,1856,1937,81,0,Intérieur Parisien,0,USD,8125.00,4000.0,...,1,(55.6 x 45.9 cm.),20,American Art Online,NaN,NaN,NaN,11,18,0
1186,"mitelli, giuseppe maria",1634,1718,84,0,NaN,0,USD,17187.50,2500.0,...,1,(365 x 248mm to 403 x 277mm),15,THE ROYAL HOUSE OF SAVOY,NaN,NaN,NaN,10,19,0

In [132]:
ArtInfo.to_csv("Christies_Art_Objects_Clean.csv", index = False)